import type { FormulaEntry } from './formulaTypes';

/** The active network follows the exam-review scan: k4 and k5 are in series. */
const activeNetworkFormulas: FormulaEntry[] = [
  {
    id: 'network-equivalent-stiffness',
    title: 'Reduce the active spring network',
    scope: 'network',
    group: 'Equivalent stiffness',
    tex: [
      String.raw`k_{45}=\left(\frac{1}{k_4}+\frac{1}{k_5}\right)^{-1}=\frac{k_4k_5}{k_4+k_5}`,
      String.raw`k_{\mathrm{eq}}=k_1+k_2+k_3+k_{45}`,
    ],
    description: 'The exam diagram has k1 and k2 above the mass, k3 directly below, and k4 followed by k5 in the lower right branch. The four complete load paths contribute in parallel.',
    usage: 'This is the equivalent stiffness used by the active spring-network simulation. The Topic 4 practice photo has different spring numbering; its reduction appears in a separate reference group.',
    sources: ['Adobe Scan Oct 4, 2026.pdf'],
    reconstructed: true,
    tags: ['network', 'series', 'parallel', 'stiffness', 'k45'],
  },
  {
    id: 'network-junction',
    title: 'Where the massless junction moves',
    scope: 'network',
    group: 'Signed deformation and branch forces',
    tex: [
      String.raw`k_4(x-y)-k_5y=0`,
      String.raw`y=\frac{k_4}{k_4+k_5}x`,
    ],
    description: 'x is downward mass displacement; y is downward displacement of the connector between k4 and k5. Both start at the statically loaded equilibrium. The connector has no mass, so its incremental force balance is zero.',
    usage: 'The drawing moves this connector by the same y calculated here. A softer k4 takes more deformation, leaving a smaller connector movement.',
    sources: ['Adobe Scan Oct 4, 2026.pdf'],
    reconstructed: true,
    tags: ['junction', 'massless', 'force balance', 'series', 'position'],
  },
  {
    id: 'network-signed-extensions',
    title: 'Signed changes in spring length',
    scope: 'network',
    group: 'Signed deformation and branch forces',
    tex: [
      String.raw`\delta_1=\delta_2=x,\qquad\delta_3=-x`,
      String.raw`\delta_4=y-x=-\frac{k_5}{k_4+k_5}x`,
      String.raw`\delta_5=-y=-\frac{k_4}{k_4+k_5}x`,
      String.raw`\delta_4+\delta_5=-x`,
    ],
    description: 'A positive elongation is an increase in spring length relative to static equilibrium. Downward mass motion stretches the upper springs and compresses the lower springs.',
    usage: 'These are the signed deformations shown by the active branch readouts. They are increments about equilibrium, not the springs’ absolute loaded lengths.',
    sources: ['Adobe Scan Oct 4, 2026.pdf'],
    reconstructed: true,
    tags: ['signs', 'extension', 'compression', 'x', 'y', 'geometry'],
  },
  {
    id: 'network-branch-forces',
    title: 'Each branch pulls toward equilibrium',
    scope: 'network',
    group: 'Signed deformation and branch forces',
    tex: [
      String.raw`F_1=-k_1x,\qquad F_2=-k_2x`,
      String.raw`F_3=k_3\delta_3=-k_3x`,
      String.raw`F_{45}=k_4\delta_4=k_5\delta_5=-k_{45}x`,
      String.raw`F_{\mathrm{spring}}=F_1+F_2+F_3+F_{45}=-k_{\mathrm{eq}}x`,
    ],
    description: 'Force is positive downward. Both upper tension forces and lower compression forces oppose a positive displacement. k4 and k5 transmit one common series-branch force.',
    usage: 'Count the series branch once when summing forces on the mass. Adding the k4 and k5 force readouts as separate load paths would double-count that branch.',
    sources: ['Adobe Scan Oct 4, 2026.pdf'],
    reconstructed: true,
    tags: ['Newton', 'Hooke', 'forces', 'signs', 'series'],
  },
  {
    id: 'network-loaded-equilibrium',
    title: 'Why gravity drops out of the vibration equation',
    scope: 'network',
    group: 'Equation of motion and natural frequency',
    tex: [
      String.raw`mg+F_{\mathrm{spring,static}}=0`,
      String.raw`m\ddot x=mg+F_{\mathrm{spring,static}}-k_{\mathrm{eq}}x=-k_{\mathrm{eq}}x`,
    ],
    description: 'The vertical coordinate is measured from the loaded equilibrium where the spring preload balances weight. Incremental motion is governed by the additional spring restoring force.',
    usage: 'Gravity shifts the resting position of an ideal linear spring network. It does not change its small-motion natural frequency. This cancellation is different from the pendulum, whose changing gravity torque contributes stiffness.',
    sources: ['Adobe Scan Oct 4, 2026.pdf', 'IMG_5927.HEIC'],
    reconstructed: true,
    tags: ['gravity', 'equilibrium', 'preload', 'vertical', 'coordinate'],
  },
  {
    id: 'network-newton-eom',
    title: 'Newton’s law gives the equation of motion',
    scope: 'network',
    group: 'Equation of motion and natural frequency',
    tex: [
      String.raw`\sum F=m\ddot x`,
      String.raw`-k_{\mathrm{eq}}x=m\ddot x`,
      String.raw`m\ddot x+k_{\mathrm{eq}}x=0`,
      String.raw`\ddot x+\frac{k_{\mathrm{eq}}}{m}x=0`,
    ],
    description: 'The exam asks for Newton’s-law derivation after equivalent stiffness is found. Moving the restoring-force term to the left gives the linear undamped equation.',
    usage: 'This equation is evaluated by the active simulation. Its two left-hand terms sum to zero at every sampled time.',
    sources: ['Adobe Scan Oct 4, 2026.pdf'],
    reconstructed: true,
    tags: ['EOM', 'Newton', 'acceleration', 'undamped'],
  },
  {
    id: 'network-frequency-period',
    title: 'Angular frequency, frequency, and period',
    scope: 'network',
    group: 'Equation of motion and natural frequency',
    tex: [
      String.raw`\omega_n=\sqrt{\frac{k_{\mathrm{eq}}}{m}}\quad[\mathrm{rad/s}]`,
      String.raw`f_n=\frac{\omega_n}{2\pi}\quad[\mathrm{Hz}]`,
      String.raw`T_n=\frac{1}{f_n}=\frac{2\pi}{\omega_n}\quad[\mathrm{s}]`,
    ],
    description: 'The coefficient multiplying x in the normalized equation is ωn squared. Angular frequency counts radians per second; frequency counts cycles per second; period is seconds per cycle.',
    usage: 'Increasing equivalent stiffness speeds the oscillation. Increasing mass slows it. Changing release amplitude leaves frequency unchanged in this linear model.',
    sources: ['Adobe Scan Oct 4, 2026.pdf', 'IMG_5928.HEIC', 'IMG_5929.HEIC'],
    reconstructed: true,
    tags: ['frequency', 'period', 'omega', 'Hz', 'units'],
  },
  {
    id: 'network-response-derivatives',
    title: 'Position, velocity, and acceleration from the release',
    scope: 'network',
    group: 'Analytical motion',
    tex: [
      String.raw`x(t)=x_0\cos(\omega_nt)+\frac{v_0}{\omega_n}\sin(\omega_nt)`,
      String.raw`\dot x(t)=-\omega_nx_0\sin(\omega_nt)+v_0\cos(\omega_nt)`,
      String.raw`\ddot x(t)=-\omega_n^2x(t)`,
      String.raw`A=\sqrt{x_0^2+\left(\frac{v_0}{\omega_n}\right)^2}`,
    ],
    description: 'Differentiate the initial-condition response to obtain velocity and acceleration. A nonzero initial velocity introduces a sine term and can increase amplitude beyond the initial displacement.',
    usage: 'Playback, graph samples, and scrubbing all evaluate this same analytical trajectory. x0 and v0 are editable initial conditions.',
    sources: ['Adobe Scan Oct 4, 2026.pdf'],
    reconstructed: true,
    tags: ['initial conditions', 'derivative', 'response', 'cosine', 'sine', 'amplitude'],
  },
  {
    id: 'network-series-energy',
    title: 'Energy stored in the series branch',
    scope: 'network',
    group: 'Energy',
    tex: [
      String.raw`V_{45}=\frac12k_4\delta_4^2+\frac12k_5\delta_5^2`,
      String.raw`V_{45}=\frac12\frac{k_4k_5}{k_4+k_5}x^2=\frac12k_{45}x^2`,
    ],
    description: 'Substitute the signed spring-length changes into the sum of individual quadratic spring energies. Their signs disappear when squared, producing the equivalent branch stiffness.',
    usage: 'This is another way to verify the series reduction. The energy is counted once for the complete branch even though it is stored in two springs.',
    sources: ['Adobe Scan Oct 4, 2026.pdf', 'IMG_5927.HEIC'],
    reconstructed: true,
    tags: ['potential', 'energy', 'series', 'equivalent stiffness'],
  },
  {
    id: 'network-energy-conservation',
    title: 'Vibration energy about the loaded equilibrium',
    scope: 'network',
    group: 'Energy',
    tex: [
      String.raw`T=\frac12m\dot x^2,\qquad V=\frac12k_{\mathrm{eq}}x^2`,
      String.raw`E=T+V=\frac12mv_0^2+\frac12k_{\mathrm{eq}}x_0^2=\frac12k_{\mathrm{eq}}A^2`,
      String.raw`\frac{dE}{dt}=\dot x\left(m\ddot x+k_{\mathrm{eq}}x\right)=0`,
    ],
    description: 'Potential is measured relative to loaded equilibrium. Linear changes in gravity energy and static spring-preload energy cancel, leaving the quadratic motion energy.',
    usage: 'The active energy bars trade kinetic and potential energy without loss. No extra positive gravity-energy bar belongs in this equilibrium-coordinate network model.',
    sources: ['Adobe Scan Oct 4, 2026.pdf', 'IMG_5927.HEIC'],
    reconstructed: true,
    tags: ['energy', 'conservation', 'kinetic', 'potential', 'derivative'],
  },
];

const lectureAndFoundationFormulas: FormulaEntry[] = [
  {
    id: "lecture-linearization",
    title: "Tangent-line linearization",
    scope: "shared",
    group: "Linearization and trigonometry",
    tex: [String.raw`L(x)=f(a)+f\prime(a)(x-a)`],
    description: "Valid near a for differentiable f; L here is the linearization function, not rod length.",
    usage: "These foundations support the active pendulum approximation. They do not make the animation a nonlinear large-angle solver.",
    sources: ["IMG_5923.HEIC"],
    tags: ["linearization", "Taylor", "trigonometry", "pendulum", "derivative", "linearization"],
  },
  {
    id: "lecture-sin-linearization",
    title: "Sine at zero",
    scope: "shared",
    group: "Linearization and trigonometry",
    tex: [String.raw`L(x)=\sin 0+\cos 0\,x=x`],
    description: "The independent angle must be in radians.",
    usage: "These foundations support the active pendulum approximation. They do not make the animation a nonlinear large-angle solver.",
    sources: ["IMG_5923.HEIC"],
    tags: ["linearization", "Taylor", "trigonometry", "pendulum", "derivative", "sin", "linearization"],
  },
  {
    id: "lecture-small-angle-sin",
    title: "Small-angle sine",
    scope: "shared",
    group: "Linearization and trigonometry",
    tex: [String.raw`\sin\theta\simeq\theta`],
    description: "The small-angle pendulum is built by approximating trigonometric functions near zero.",
    usage: "These foundations support the active pendulum approximation. They do not make the animation a nonlinear large-angle solver.",
    sources: ["IMG_5923.HEIC"],
    tags: ["linearization", "Taylor", "trigonometry", "pendulum", "derivative", "small", "angle", "sin"],
  },
  {
    id: "lecture-small-angle-cos",
    title: "Small-angle cosine",
    scope: "shared",
    group: "Linearization and trigonometry",
    tex: [String.raw`\cos\theta\simeq1`],
    description: "The small-angle pendulum is built by approximating trigonometric functions near zero.",
    usage: "These foundations support the active pendulum approximation. They do not make the animation a nonlinear large-angle solver.",
    sources: ["IMG_5923.HEIC"],
    tags: ["linearization", "Taylor", "trigonometry", "pendulum", "derivative", "small", "angle", "cos"],
  },
  {
    id: "lecture-small-angle-tan",
    title: "Small-angle tangent",
    scope: "shared",
    group: "Linearization and trigonometry",
    tex: [String.raw`\tan\theta\simeq\theta`],
    description: "The small-angle pendulum is built by approximating trigonometric functions near zero.",
    usage: "These foundations support the active pendulum approximation. They do not make the animation a nonlinear large-angle solver.",
    sources: ["IMG_5923.HEIC"],
    tags: ["linearization", "Taylor", "trigonometry", "pendulum", "derivative", "small", "angle", "tan"],
  },
  {
    id: "lecture-trig-derivatives",
    title: "Trigonometric derivative steps",
    scope: "shared",
    group: "Linearization and trigonometry",
    tex: [String.raw`\frac{d}{d\theta}\sin\theta=\cos\theta,\quad\frac{d}{d\theta}\cos\theta=-\sin\theta,\quad\frac{d}{d\theta}\tan\theta=\sec^2\theta`],
    description: "Not explicitly printed; supplies the derivatives used in the tangent-line construction.",
    usage: "These foundations support the active pendulum approximation. They do not make the animation a nonlinear large-angle solver.",
    sources: ["IMG_5923.HEIC"],
    reconstructed: true,
    tags: ["linearization", "Taylor", "trigonometry", "pendulum", "derivative", "trig", "derivatives"],
  },
  {
    id: "lecture-trig-values-zero",
    title: "Values used at equilibrium",
    scope: "shared",
    group: "Linearization and trigonometry",
    tex: [String.raw`\sin0=0,\quad\cos0=1,\quad\tan0=0,\quad\sec^2 0=1`],
    description: "The small-angle pendulum is built by approximating trigonometric functions near zero.",
    usage: "These foundations support the active pendulum approximation. They do not make the animation a nonlinear large-angle solver.",
    sources: ["IMG_5923.HEIC"],
    reconstructed: true,
    tags: ["linearization", "Taylor", "trigonometry", "pendulum", "derivative", "trig", "values", "zero"],
  },
  {
    id: "lecture-small-angle-taylor",
    title: "Taylor terms behind the approximation",
    scope: "shared",
    group: "Linearization and trigonometry",
    tex: [String.raw`\sin\theta=\theta-\frac{\theta^3}{6}+\cdots,\quad\cos\theta=1-\frac{\theta^2}{2}+\cdots,\quad\tan\theta=\theta+\frac{\theta^3}{3}+\cdots`],
    description: "Photo names the Taylor series but only prints the leading approximations. Keeping the quadratic cosine term gives the pendulum gravitational energy.",
    usage: "These foundations support the active pendulum approximation. They do not make the animation a nonlinear large-angle solver.",
    sources: ["IMG_5923.HEIC"],
    reconstructed: true,
    tags: ["linearization", "Taylor", "trigonometry", "pendulum", "derivative", "small", "angle", "taylor"],
  },
  {
    id: "lecture-stiffness-force-displacement",
    title: "Linear stiffness definition",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`k=\frac{P}{\delta},\qquad P=k\delta`],
    description: "P is the applied load magnitude. The restoring force on a displaced mass is −kx; do not confuse its sign with the load definition.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5925.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "stiffness", "force", "displacement"],
  },
  {
    id: "lecture-axial-stress",
    title: "Axial stress",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`\sigma=\frac{P}{A}`],
    description: "An elastic structural element can act as an equivalent spring. The source leaves these formulas blank, so the standard relations are reconstructed.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5925.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "axial", "stress"],
  },
  {
    id: "lecture-axial-strain",
    title: "Axial strain and Hooke law",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`\varepsilon=\frac{\delta}{\ell}=\frac{\sigma}{E}`],
    description: "An elastic structural element can act as an equivalent spring. The source leaves these formulas blank, so the standard relations are reconstructed.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5925.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "axial", "strain"],
  },
  {
    id: "lecture-axial-elongation",
    title: "Rod elongation chain",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`\delta=\varepsilon\ell=\frac{\sigma\ell}{E}=\frac{P\ell}{EA}`],
    description: "An elastic structural element can act as an equivalent spring. The source leaves these formulas blank, so the standard relations are reconstructed.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5925.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "axial", "elongation"],
  },
  {
    id: "lecture-axial-rod-stiffness",
    title: "Prismatic rod stiffness",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`P=\frac{EA}{\ell}\delta,\qquad k=\frac{EA}{\ell}`],
    description: "E Young modulus, A cross-sectional area, ℓ rod length; longitudinal vibration, uniform prismatic massless rod.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5925.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "axial", "rod", "stiffness"],
  },
  {
    id: "lecture-helical-spring-stiffness",
    title: "Close-coiled helical spring stiffness",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`k=\frac{Gd^4}{8D^3n}=\frac{Gd^4}{64r^3n},\qquad D=2r`],
    description: "Photo defines d as wire diameter, 2r as coil diameter, n number of turns, G shear modulus. Elastic deformation comes chiefly from wire torsion.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5925.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "helical", "spring", "stiffness"],
  },
  {
    id: "lecture-cantilever-deflection",
    title: "Cantilever tip deflection",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`\delta=\frac{P\ell^3}{3EI}`],
    description: "Derived supporting step for the blank beam stiffness; point load at free tip, uniform Euler–Bernoulli beam, beam mass neglected.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5926.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "cantilever", "deflection"],
  },
  {
    id: "lecture-cantilever-stiffness",
    title: "Cantilever tip stiffness",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`k=\frac{3EI}{\ell^3}`],
    description: "I is the area second moment about the bending axis; E Young modulus. Linear stiffness units N/m.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5926.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "cantilever", "stiffness"],
  },
  {
    id: "lecture-shaft-torsion",
    title: "Prismatic shaft torsional stiffness",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`\theta=\frac{\tau\ell}{GJ_p},\qquad k_\theta=\frac{\tau}{\theta}=\frac{GJ_p}{\ell}`],
    description: "J_p is a geometric polar area moment (m^4), distinct from the disk mass moment J (kg m^2). Rotational stiffness units N m/rad.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5926.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "shaft", "torsion"],
  },
  {
    id: "lecture-spiral-torsion",
    title: "Spiral strip spring stiffness",
    scope: "lecture",
    group: "Structural stiffness · reference",
    tex: [String.raw`k_\theta=\frac{EI}{\ell}`],
    description: "Source depicts a planar spiral coil and defines E, I, total strip length ℓ; this is the ideal bending-strip relation, not the helical axial spring formula.",
    usage: "Reference background only: neither active simulation models rod strain, beam bending, shaft twist, or spiral-strip deformation.",
    sources: ["IMG_5926.HEIC"],
    reconstructed: true,
    tags: ["stiffness", "structure", "rod", "beam", "shaft", "torsion", "spiral", "torsion"],
  },
  {
    id: "network-parallel-static-balance",
    title: "Generic pair: Parallel load balance",
    scope: "network",
    group: "Equivalent stiffness",
    tex: [String.raw`W=mg=k_a\delta_{st}+k_b\delta_{st}=(k_a+k_b)\delta_{st}`],
    description: "Parallel springs share the same endpoint deformation. Source terminology should read same deformation.",
    usage: "These are generic isolated springs labeled a and b; the photo’s labels are renamed to avoid confusion. In the active diagram k1 and k2 are parallel, while only k4 and k5 form the series pair. W denotes the load on this isolated example, not an individual active-branch load.",
    sources: ["IMG_5927.HEIC"],
    tags: ["series", "parallel", "equilibrium", "network", "parallel", "static", "balance"],
  },
  {
    id: "network-parallel-stiffness",
    title: "Parallel stiffness",
    scope: "network",
    group: "Equivalent stiffness",
    tex: [String.raw`k_{eq}=\sum_{i=1}^{n}k_i`],
    description: "Series and parallel reduction connect the separate spring forces to an equivalent force-displacement law.",
    usage: "Use the reduction rules in the active network, while preserving its specific k4–k5 series branch and equilibrium-coordinate signs.",
    sources: ["IMG_5927.HEIC"],
    tags: ["series", "parallel", "equilibrium", "network", "parallel", "stiffness"],
  },
  {
    id: "network-series-static-force",
    title: "Generic pair: Common force in series",
    scope: "network",
    group: "Equivalent stiffness",
    tex: [String.raw`W=k_a\delta_a=k_b\delta_b,\qquad\delta_a=\frac{W}{k_a},\quad\delta_b=\frac{W}{k_b}`],
    description: "Series and parallel reduction connect the separate spring forces to an equivalent force-displacement law.",
    usage: "These are generic isolated springs labeled a and b; the photo’s labels are renamed to avoid confusion. In the active diagram k1 and k2 are parallel, while only k4 and k5 form the series pair. W denotes the load on this isolated example, not an individual active-branch load.",
    sources: ["IMG_5927.HEIC"],
    tags: ["series", "parallel", "equilibrium", "network", "series", "static", "force"],
  },
  {
    id: "network-series-total-extension",
    title: "Generic pair: Series total extension",
    scope: "network",
    group: "Equivalent stiffness",
    tex: [String.raw`\delta_{st}=\delta_a+\delta_b=W\left(\frac{1}{k_a}+\frac{1}{k_b}\right),\qquad W=k_{eq}\delta_{st}`],
    description: "Series and parallel reduction connect the separate spring forces to an equivalent force-displacement law.",
    usage: "These are generic isolated springs labeled a and b; the photo’s labels are renamed to avoid confusion. In the active diagram k1 and k2 are parallel, while only k4 and k5 form the series pair. W denotes the load on this isolated example, not an individual active-branch load.",
    sources: ["IMG_5927.HEIC"],
    tags: ["series", "parallel", "equilibrium", "network", "series", "total", "extension"],
  },
  {
    id: "network-series-stiffness-general",
    title: "Series equivalent stiffness",
    scope: "network",
    group: "Equivalent stiffness",
    tex: [String.raw`\frac{1}{k_{eq}}=\sum_{i=1}^{n}\frac{1}{k_i},\qquad k_{eq}=\left(\sum_{i=1}^{n}\frac{1}{k_i}\right)^{-1}`],
    description: "The final handwritten general series sum appears to end with +k_n; it must end with +1/k_n.",
    usage: "Use the reduction rules in the active network, while preserving its specific k4–k5 series branch and equilibrium-coordinate signs.",
    sources: ["IMG_5927.HEIC"],
    reconstructed: true,
    correction: "The final handwritten general series sum appears to end with +k_n; it must end with +1/k_n.",
    tags: ["series", "parallel", "equilibrium", "network", "series", "stiffness", "general"],
  },
  {
    id: "network-series-two-springs",
    title: "Generic pair: Two springs in series",
    scope: "network",
    group: "Equivalent stiffness",
    tex: [String.raw`k_{eq}=\frac{k_ak_b}{k_a+k_b}`],
    description: "Series and parallel reduction connect the separate spring forces to an equivalent force-displacement law.",
    usage: "These are generic isolated springs labeled a and b; the photo’s labels are renamed to avoid confusion. In the active diagram k1 and k2 are parallel, while only k4 and k5 form the series pair. W denotes the load on this isolated example, not an individual active-branch load.",
    sources: ["IMG_5927.HEIC"],
    tags: ["series", "parallel", "equilibrium", "network", "series", "two", "springs"],
  },
  {
    id: "network-static-deflection",
    title: "Static deflection of a vertical equivalent spring",
    scope: "network",
    group: "Equivalent stiffness",
    tex: [String.raw`\delta_{st}=\frac{mg}{k_{eq}}`],
    description: "The implemented network uses x from loaded equilibrium. These static deflection magnitudes are not its dynamic x.",
    usage: "Use the reduction rules in the active network, while preserving its specific k4–k5 series branch and equilibrium-coordinate signs.",
    sources: ["IMG_5927.HEIC"],
    reconstructed: true,
    tags: ["series", "parallel", "equilibrium", "network", "static", "deflection"],
  },
  {
    id: "lecture-practice-series34",
    title: "Practice series pair",
    scope: "lecture",
    group: "Topic 4 · alternate network",
    tex: [String.raw`k_{34}=\left(\frac{1}{k_3}+\frac{1}{k_4}\right)^{-1}=\frac{k_3k_4}{k_3+k_4}`],
    description: "The photo uses k3,k4 in series, with k5 direct. The exam simulator uses k4,k5 in series, with k3 direct. Do not substitute this formula into the implemented diagram.",
    usage: "Related example only. It differs from the active exam diagram, which puts k4 and k5 in series and makes k3 the direct lower branch.",
    sources: ["IMG_5928.HEIC"],
    tags: ["network", "alternate diagram", "practice", "k34", "stiffness", "practice", "series34"],
  },
  {
    id: "lecture-practice-keq",
    title: "Practice equivalent stiffness",
    scope: "lecture",
    group: "Topic 4 · alternate network",
    tex: [String.raw`k_{eq}=k_1+k_2+k_5+\frac{k_3k_4}{k_3+k_4}`],
    description: "This photographed practice diagram places k3 and k4 in series, with k5 as the direct lower branch.",
    usage: "Related example only. It differs from the active exam diagram, which puts k4 and k5 in series and makes k3 the direct lower branch.",
    sources: ["IMG_5928.HEIC"],
    tags: ["network", "alternate diagram", "practice", "k34", "stiffness", "practice", "keq"],
  },
  {
    id: "lecture-practice-keq-expanded",
    title: "Practice stiffness as one fraction",
    scope: "lecture",
    group: "Topic 4 · alternate network",
    tex: [String.raw`k_{eq}=\frac{(k_1+k_2+k_5)(k_3+k_4)+k_3k_4}{k_3+k_4}`],
    description: "This photographed practice diagram places k3 and k4 in series, with k5 as the direct lower branch.",
    usage: "Related example only. It differs from the active exam diagram, which puts k4 and k5 in series and makes k3 the direct lower branch.",
    sources: ["IMG_5928.HEIC"],
    tags: ["network", "alternate diagram", "practice", "k34", "stiffness", "practice", "keq", "expanded"],
  },
  {
    id: "lecture-practice-frequency",
    title: "Practice natural angular frequency",
    scope: "lecture",
    group: "Topic 4 · alternate network",
    tex: [String.raw`\omega_n=\sqrt{\frac{k_{eq}}{m}}=\sqrt{\frac{k_1k_3+k_2k_3+k_3k_5+k_1k_4+k_2k_4+k_4k_5+k_3k_4}{m(k_3+k_4)}}`],
    description: "This photographed practice diagram places k3 and k4 in series, with k5 as the direct lower branch.",
    usage: "Related example only. It differs from the active exam diagram, which puts k4 and k5 in series and makes k3 the direct lower branch.",
    sources: ["IMG_5928.HEIC"],
    tags: ["network", "alternate diagram", "practice", "k34", "stiffness", "practice", "frequency"],
  },
  {
    id: "lecture-beam-frequency",
    title: "Beam tip-mass natural frequency",
    scope: "lecture",
    group: "Diving board · worked example",
    tex: [String.raw`\omega_n=2\pi f_n=\sqrt{\frac{k}{m}}=\sqrt{\frac{3EI}{m\ell^3}}`],
    description: "Source gives m=100 kg, effective ℓ=1.5 m, f=3 Hz. Beam mass neglected.",
    usage: "Related Topic 4 example only: the active simulations do not animate a diving board or model beam distributed mass.",
    sources: ["IMG_5929.HEIC"],
    reconstructed: true,
    tags: ["beam", "diving board", "frequency", "flexural rigidity", "EI", "beam", "frequency"],
  },
  {
    id: "lecture-beam-rigidity",
    title: "Required flexural rigidity",
    scope: "lecture",
    group: "Diving board · worked example",
    tex: [String.raw`EI=\frac{m\ell^3(2\pi f_n)^2}{3}`],
    description: "A diver at the tip of a massless cantilever is represented by a tip mass on an equivalent transverse spring.",
    usage: "Related Topic 4 example only: the active simulations do not animate a diving board or model beam distributed mass.",
    sources: ["IMG_5929.HEIC"],
    reconstructed: true,
    tags: ["beam", "diving board", "frequency", "flexural rigidity", "EI", "beam", "rigidity"],
  },
  {
    id: "lecture-beam-rigidity-result",
    title: "Diving board worked result",
    scope: "lecture",
    group: "Diving board · worked example",
    tex: [String.raw`EI=\frac{100(1.5)^3(2\pi\cdot3)^2}{3}\simeq4.00\times10^4\;\mathrm{N\,m^2}`],
    description: "The answer value is printed in the source; intermediate solution is blank.",
    usage: "Related Topic 4 example only: the active simulations do not animate a diving board or model beam distributed mass.",
    sources: ["IMG_5929.HEIC"],
    reconstructed: true,
    tags: ["beam", "diving board", "frequency", "flexural rigidity", "EI", "beam", "rigidity", "result"],
  },
  {
    id: "lecture-viscous-force",
    title: "Viscous damper force",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`F_d=-c\dot x,\qquad[c]=\mathrm{N\,s/m}=\mathrm{kg/s}`],
    description: "Photo writes F=c dx/dt=c xdot for the applied force/magnitude required to drive a dashpot. Force exerted on the vibrating mass opposes velocity, hence −c xdot.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5930.HEIC"],
    reconstructed: true,
    correction: "Photo writes F=c dx/dt=c xdot for the applied force/magnitude required to drive a dashpot. Force exerted on the vibrating mass opposes velocity, hence −c xdot.",
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "viscous", "force"],
  },
  {
    id: "lecture-damped-newton",
    title: "Newton force balance with damping",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`-kx-c\dot x=m\ddot x`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5931.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "damped", "newton"],
  },
  {
    id: "lecture-damped-eom",
    title: "Damped free-vibration equation",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`m\ddot x+c\dot x+kx=0`],
    description: "Second-order linear homogeneous ODE. Set c=0 to obtain the active network model.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5931.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "damped", "eom"],
  },
  {
    id: "lecture-exponential-ansatz",
    title: "Exponential trial solution",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`x=C e^{\lambda t},\qquad\dot x=C\lambda e^{\lambda t},\qquad\ddot x=C\lambda^2e^{\lambda t}`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5931.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "exponential", "ansatz"],
  },
  {
    id: "lecture-characteristic-substitution",
    title: "Substitution and characteristic equation",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`(m\lambda^2+c\lambda+k)Ce^{\lambda t}=0\quad\Longrightarrow\quad m\lambda^2+c\lambda+k=0`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5931.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "characteristic", "substitution"],
  },
  {
    id: "lecture-quadratic-formula",
    title: "Quadratic formula used for roots",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`az^2+bz+d=0\quad\Longrightarrow\quad z=\frac{-b\pm\sqrt{b^2-4ad}}{2a}`],
    description: "d labels the polynomial constant here to avoid confusing it with the damping c.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5931.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "quadratic", "formula"],
  },
  {
    id: "lecture-characteristic-roots",
    title: "Characteristic roots",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`\lambda_{1,2}=\frac{-c\pm\sqrt{c^2-4mk}}{2m}=-\frac{c}{2m}\pm\sqrt{\left(\frac{c}{2m}\right)^2-\frac{k}{m}}`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5931.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "characteristic", "roots"],
  },
  {
    id: "lecture-distinct-root-response",
    title: "Distinct-root response",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`x(t)=C_1 e^{\lambda_1t}+C_2e^{\lambda_2t}`],
    description: "This pair spans the solution only when λ1 and λ2 are distinct. Critical damping has a repeated root and needs a t multiplier.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5931.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "distinct", "root", "response"],
  },
  {
    id: "lecture-initial-constants-distinct",
    title: "Initial-condition constants for distinct roots",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`C_1+C_2=x_0,\quad\lambda_1C_1+\lambda_2C_2=v_0,\quad C_1=\frac{v_0-\lambda_2x_0}{\lambda_1-\lambda_2},\quad C_2=\frac{\lambda_1x_0-v_0}{\lambda_1-\lambda_2}`],
    description: "Source says constants come from initial conditions; these explicit steps complete that calculation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5931.HEIC"],
    reconstructed: true,
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "initial", "constants", "distinct"],
  },
  {
    id: "lecture-factored-damped-response",
    title: "Factored exponential response",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`x(t)=e^{-\frac{c}{2m}t}\left[C_1e^{t\sqrt{(\frac{c}{2m})^2-\frac{k}{m}}}+C_2e^{-t\sqrt{(\frac{c}{2m})^2-\frac{k}{m}}}\right]`],
    description: "Distinct-root form; includes t in both bracketed exponents.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5932.HEIC", "IMG_5933.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "factored", "damped", "response"],
  },
  {
    id: "lecture-damping-discriminant",
    title: "Damping cases from the discriminant",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`D=\left(\frac{c}{2m}\right)^2-\frac{k}{m}:\quad D>0\;\text{overdamped},\quad D<0\;\text{underdamped},\quad D=0\;\text{critical}`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5932.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "damping", "discriminant"],
  },
  {
    id: "lecture-euler-formula",
    title: "Euler formula behind oscillatory roots",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`e^{i\theta}=\cos\theta+i\sin\theta`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5932.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "euler", "formula"],
  },
  {
    id: "lecture-critical-constant",
    title: "Critical damping constant",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`\left(\frac{c_{cr}}{2m}\right)^2-\frac{k}{m}=0,\qquad c_{cr}=2m\omega_n=2\sqrt{km}`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5933.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "critical", "constant"],
  },
  {
    id: "lecture-damping-ratio",
    title: "Damping ratio",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`\zeta=\frac{c}{c_{cr}}=\frac{c}{2m\omega_n},\qquad\frac{c}{2m}=\zeta\omega_n`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5933.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "damping", "ratio"],
  },
  {
    id: "lecture-zeta-roots",
    title: "Characteristic roots using damping ratio",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`\lambda_{1,2}=\omega_n\left(-\zeta\pm\sqrt{\zeta^2-1}\right)`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5933.HEIC"],
    reconstructed: true,
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "zeta", "roots"],
  },
  {
    id: "lecture-zeta-general-response",
    title: "Response using damping ratio",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`x(t)=e^{-\zeta\omega_nt}\left[C_1e^{\omega_nt\sqrt{\zeta^2-1}}+C_2e^{-\omega_nt\sqrt{\zeta^2-1}}\right]`],
    description: "Use only for distinct roots (ζ≠1). For ζ<1 the square root is imaginary and Euler formula gives sine/cosine terms.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5933.HEIC", "IMG_5934.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "zeta", "general", "response"],
  },
  {
    id: "lecture-zeta-classification",
    title: "Damping ratio ranges",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`\zeta=0\;\text{undamped},\quad0<\zeta<1\;\text{underdamped},\quad\zeta=1\;\text{critical},\quad\zeta>1\;\text{overdamped}`],
    description: "The Topic 5 lecture adds a viscous force proportional to velocity and solves the resulting homogeneous equation.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5933.HEIC"],
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "zeta", "classification"],
  },
  {
    id: "lecture-critical-response-correction",
    title: "Repeated-root critical response",
    scope: "lecture",
    group: "Viscous damping · reference",
    tex: [String.raw`x(t)=(C_1+C_2t)e^{-\omega_nt}=\left[x_0+(v_0+\omega_nx_0)t\right]e^{-\omega_nt}`],
    description: "Required exception to the displayed distinct-root formula at ζ=1; not printed on this page. Critical damping is the threshold for nonoscillatory homogeneous modes; zero crossings can still occur for suitable nonzero initial velocity.",
    usage: "Reference background only. Both active exam simulations are undamped; there is no adjustable damping coefficient in their numerical model.",
    sources: ["IMG_5934.HEIC"],
    reconstructed: true,
    correction: "Required exception to the displayed distinct-root formula at ζ=1; not printed on this page. Critical damping is the threshold for nonoscillatory homogeneous modes; zero crossings can still occur for suitable nonzero initial velocity.",
    tags: ["damping", "viscous", "ODE", "characteristic roots", "lecture", "critical", "response", "correction"],
  },
];

export const networkFormulas: FormulaEntry[] = [
  ...activeNetworkFormulas,
  ...lectureAndFoundationFormulas,
];
