import type { FormulaEntry } from './formulaTypes'

/** Audited against the user’s Topic 03 photographs; reconstructed steps are labeled. */
export const pendulumFormulas: FormulaEntry[] = [
  {
    id: "pend-coordinate",
    title: "Pendulum coordinate and point-mass inertia",
    scope: "pendulum",
    group: "Geometry and inertia",
    tex: [
      String.raw`q=\theta,\qquad J_O=mL^2`,
      String.raw`[J_O]=\mathrm{kg\,m^2}`,
    ],
    description: "A concentrated bob moves at radius L about a fixed, frictionless pivot. The connecting rod has negligible mass.",
    usage: "The active angular equation uses this J rather than the mass m alone.",
    sources: ["IMG_5921.HEIC"],
    tags: ["massless rod", "inertia", "pivot", "theta"],
  },
  {
    id: "pend-projections",
    title: "Horizontal position and vertical rise",
    scope: "pendulum",
    group: "Geometry and inertia",
    tex: [
      String.raw`x_{\mathrm{draw}}=L\sin\theta`,
      String.raw`z_{\mathrm{down}}=L\cos\theta`,
      String.raw`h=L-z_{\mathrm{down}}=L(1-\cos\theta)`,
    ],
    description: "The scene uses circular pendulum geometry. h is measured upward from the bob’s lowest position.",
    usage: "These relationships position the bob, establish force moment arms, and explain gravitational potential.",
    sources: ["IMG_5921.HEIC", "IMG_5918.HEIC"],
    reconstructed: true,
    tags: ["geometry", "sin", "cos", "height"],
  },
  {
    id: "pend-linear-coordinate",
    title: "Linear comparison: displacement and its derivatives",
    scope: "pendulum",
    group: "Geometry and inertia",
    tex: [
      String.raw`x=L\theta,\quad v=L\dot\theta,\quad a=L\ddot\theta`,
      String.raw`A_x=LA_\theta`,
    ],
    description: "In linear comparison mode, spring extension is approximated by L theta. Full-trig mode uses L sin(theta) and its time derivatives.",
    usage: "These formulas apply to the small-angle comparison, not to the horizontal kinematics in full-trig mode.",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["small angle", "velocity", "acceleration", "drawing"],
  },
  {
    id: "pend-small-angle",
    title: "Linearize around the hanging equilibrium",
    scope: "pendulum",
    group: "Small-angle model",
    tex: [
      String.raw`\sin\theta=\theta+O(\theta^3)\approx\theta`,
      String.raw`\cos\theta=1-\tfrac12\theta^2+O(\theta^4)\approx1`,
      String.raw`\sin\theta\cos\theta\approx\theta`,
    ],
    description: "theta is in radians. Keeping first-order torque terms produces the selectable linear comparison model.",
    usage: "Compare this approximation with the full trigonometric torque model; their differences grow with angle.",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["Taylor", "linearization", "trigonometry"],
  },
  {
    id: "pend-horizontal-spring",
    title: "Full-trig horizontal spring force and moment arm",
    scope: "pendulum",
    group: "Force and torque",
    tex: [
      String.raw`F_{s,x}=-kx_{\mathrm{geom}}=-kL\sin\theta`,
      String.raw`d_{\perp,s}=L\cos\theta`,
    ],
    description: "The lecture idealization neglects vertical spring deflection, so the spring force remains horizontal. Full-trig mode preserves the sine extension and cosine moment arm.",
    usage: "These two geometric factors generate the full-trig spring torque.",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["Hooke", "moment arm", "spring"],
  },
  {
    id: "pend-moment-balance",
    title: "Full-trig torque balance used by the simulation",
    scope: "pendulum",
    group: "Force and torque",
    tex: [
      String.raw`\sum M_O=J_O\ddot\theta`,
      String.raw`M_g=-mgL\sin\theta`,
      String.raw`M_s=-kL^2\sin\theta\cos\theta`,
      String.raw`mL^2\ddot\theta+mgL\sin\theta+kL^2\sin\theta\cos\theta=0`,
    ],
    description: "Positive theta moves the bob right. Gravity and spring moments are retained as trigonometric functions; the pivot force has no moment about the pivot.",
    usage: "This is the active full-trig equation under the lecture’s horizontal-spring idealization. It is not a general 2D spring connected to a fixed anchor.",
    sources: ["IMG_5921.HEIC"],
    tags: ["Newton", "torque", "gravity", "derivation"],
  },
  {
    id: "pend-linear-torques",
    title: "Linear comparison: restoring torques",
    scope: "pendulum",
    group: "Force and torque",
    tex: [
      String.raw`M_g=-mgL\theta`,
      String.raw`M_s=-kL^2\theta`,
      String.raw`M_{\mathrm{restoring}}=-(mgL+kL^2)\theta`,
    ],
    description: "Gravity and the horizontal spring both increase restoring stiffness about the hanging equilibrium.",
    usage: "These are the small-angle comparison torques. Full-trig mode retains sin(theta) and sin(theta) cos(theta).",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["torque", "stiffness", "signs"],
  },
  {
    id: "pend-eom",
    title: "Linear comparison: equation of motion",
    scope: "pendulum",
    group: "Equation of motion and natural frequency",
    tex: [
      String.raw`mL^2\ddot\theta+(mgL+kL^2)\theta=0`,
      String.raw`J_O\ddot\theta+K_\theta\theta=0`,
      String.raw`J_O=mL^2,\qquad K_\theta=mgL+kL^2`,
    ],
    description: "The generalized inertia is the bob’s pivot mass moment; the generalized stiffness includes gravity and the spring.",
    usage: "This equation generates the selectable linear comparison trajectory. Full-trig mode uses the nonlinear torque equation.",
    sources: ["IMG_5921.HEIC"],
    tags: ["EOM", "active model", "stiffness", "inertia"],
  },
  {
    id: "pend-frequency",
    title: "Small-angle natural frequency and period",
    scope: "pendulum",
    group: "Equation of motion and natural frequency",
    tex: [
      String.raw`\omega_n=\sqrt{\frac{K_\theta}{J_O}}=\sqrt{\frac gL+\frac km}`,
      String.raw`f_n=\frac{\omega_n}{2\pi},\qquad T_n=\frac{2\pi}{\omega_n}`,
    ],
    description: "These are linearized natural-frequency and period values. Full-trig oscillation generally has an amplitude-dependent period; it does not have one amplitude-independent frequency.",
    usage: "Use these values as the small-angle reference. They are exact for the linear comparison, not a general finite-amplitude period.",
    sources: ["IMG_5921.HEIC", "IMG_5915.HEIC", "IMG_5916.HEIC"],
    reconstructed: true,
    tags: ["frequency", "period", "Hz", "rad/s"],
  },
  {
    id: "pend-translational-equivalent",
    title: "Linear comparison: equivalent x equation",
    scope: "pendulum",
    group: "Equation of motion and natural frequency",
    tex: [
      String.raw`m\ddot x+\left(k+\frac{mg}{L}\right)x=0`,
      String.raw`k_{\mathrm{linear}}=k+\frac{mg}{L}=\frac{K_\theta}{L^2}`,
      String.raw`F_{\mathrm{equivalent}}=-k_{\mathrm{linear}}x`,
    ],
    description: "Substitute x=L theta into the angular equation and divide by L. The equivalent force includes both gravity and spring restoring effects.",
    usage: "This total equivalent restoring force is a linear-coordinate construction. It is not the horizontal net force or spring force of the full-trig pendulum.",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["equivalent force", "linear stiffness", "coordinate transformation"],
  },
  {
    id: "pend-spring-force-live",
    title: "Linear comparison: spring force",
    scope: "pendulum",
    group: "Force and torque",
    tex: [
      String.raw`F_{s,x}=-kx=-kL\theta`,
    ],
    description: "The physical spring contribution is proportional to the linearized extension.",
    usage: "Use this force in linear comparison mode. Full-trig mode uses -kL sin(theta).",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["spring force", "Hooke", "live"],
  },
  {
    id: "pend-residual",
    title: "Linear comparison: equation balance",
    scope: "pendulum",
    group: "Equation of motion and natural frequency",
    tex: [
      String.raw`R=J_O\ddot\theta+K_\theta\theta`,
      String.raw`R=0\quad\text{for the analytical trajectory}`,
    ],
    description: "The equation’s left-hand inertial and stiffness terms cancel. The physical restoring torque is -K_theta theta.",
    usage: "This residual applies to the linear comparison. Full-trig mode uses the trigonometric restoring term in its balance.",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["residual", "verification", "signs"],
  },
  {
    id: "pend-initial-response",
    title: "Linear comparison: response from the initial release",
    scope: "pendulum",
    group: "Analytical motion",
    tex: [
      String.raw`\theta(t)=\theta_0\cos(\omega_nt)+\frac{\dot\theta_0}{\omega_n}\sin(\omega_nt)`,
      String.raw`\dot\theta(t)=-\theta_0\omega_n\sin(\omega_nt)+\dot\theta_0\cos(\omega_nt)`,
      String.raw`\ddot\theta(t)=-\omega_n^2\theta(t)`,
    ],
    description: "The two initial conditions determine the analytical small-angle solution. This sine/cosine expression does not solve the finite-angle nonlinear equation.",
    usage: "Use this exact trajectory in linear comparison mode. Full-trig mode evolves the nonlinear initial-value problem.",
    sources: ["IMG_5912.HEIC", "IMG_5915.HEIC", "IMG_5916.HEIC"],
    reconstructed: true,
    tags: ["initial conditions", "release", "velocity", "acceleration"],
  },
  {
    id: "pend-angular-amplitude",
    title: "Linear comparison: amplitude from initial conditions",
    scope: "pendulum",
    group: "Analytical motion",
    tex: [
      String.raw`A_\theta=\sqrt{\theta_0^2+\left(\dot\theta_0/\omega_n\right)^2}`,
      String.raw`A_x=LA_\theta`,
    ],
    description: "Both initial angle and initial angular velocity contribute to the peak amplitude.",
    usage: "This formula is exact for linear comparison. The full-trig turning angle follows its nonlinear potential energy instead.",
    sources: ["IMG_5910.HEIC", "IMG_5915.HEIC", "IMG_5913.HEIC"],
    reconstructed: true,
    tags: ["amplitude", "initial conditions"],
  },
  {
    id: "pend-kinetic-energy",
    title: "Pendulum kinetic energy",
    scope: "pendulum",
    group: "Energy",
    tex: [
      String.raw`T=\tfrac12J_O\dot\theta^2=\tfrac12mL^2\dot\theta^2=\tfrac12m v_{\mathrm{bob}}^2`,
      String.raw`v_{\mathrm{bob}}=L|\dot\theta|`,
    ],
    description: "The massless rod stores no kinetic energy. Total bob speed follows the circular path; it is not just the horizontal velocity in full-trig mode.",
    usage: "Both modes use rotational kinetic energy. Do not substitute horizontal velocity alone into the full-trig kinetic-energy formula.",
    sources: ["IMG_5917.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["kinetic", "energy", "rotation"],
  },
  {
    id: "pend-gravity-energy",
    title: "Gravitational energy in full-trig and linear modes",
    scope: "pendulum",
    group: "Energy",
    tex: [
      String.raw`U_{g,\mathrm{geometry}}=mgL(1-\cos\theta)`,
      String.raw`1-\cos\theta\approx\tfrac12\theta^2`,
      String.raw`U_{g,\mathrm{linear}}=\tfrac12mgL\theta^2`,
    ],
    description: "Full-trig mode uses the exact rise L(1-cos theta). The linear comparison uses the quadratic small-angle potential.",
    usage: "Choose the energy consistent with the selected torque model; mixing exact potential with the linear trajectory would not conserve the same energy.",
    sources: ["IMG_5918.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["potential", "gravity", "Taylor", "small angle"],
  },
  {
    id: "pend-spring-energy",
    title: "Linear comparison: spring potential",
    scope: "pendulum",
    group: "Energy",
    tex: [
      String.raw`U_s=\tfrac12kx^2=\tfrac12kL^2\theta^2`,
    ],
    description: "Use the active linear extension x=L theta.",
    usage: "This is spring energy in linear comparison mode. Full-trig mode uses one-half k L-squared sin-squared theta.",
    sources: ["IMG_5917.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["potential", "spring", "energy"],
  },
  {
    id: "pend-total-energy",
    title: "Linear comparison: constant vibration energy",
    scope: "pendulum",
    group: "Energy",
    tex: [
      String.raw`U=U_g+U_s=\tfrac12(mgL+kL^2)\theta^2=\tfrac12K_\theta\theta^2`,
      String.raw`E=T+U=\tfrac12J_O\dot\theta^2+\tfrac12K_\theta\theta^2`,
      String.raw`E=\tfrac12J_O\dot\theta_0^2+\tfrac12K_\theta\theta_0^2=\tfrac12K_\theta A_\theta^2`,
    ],
    description: "No damping or forcing removes or supplies energy. Kinetic and potential energy exchange while their sum stays constant.",
    usage: "These expressions generate and check the linear comparison energy traces. Full-trig mode uses trigonometric potential energy.",
    sources: ["IMG_5917.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["conservation", "total energy", "amplitude"],
  },
  {
    id: "pend-energy-chain",
    title: "Linear comparison: differentiate its energy",
    scope: "pendulum",
    group: "Energy and Lagrange derivation",
    tex: [
      String.raw`\frac{dT}{dt}=J_O\dot\theta\ddot\theta`,
      String.raw`\frac{dU}{dt}=K_\theta\theta\dot\theta`,
      String.raw`\frac{dE}{dt}=\dot\theta\left(J_O\ddot\theta+K_\theta\theta\right)=0`,
    ],
    description: "The chain rule brings down a factor 2 from each square and a time derivative of its argument.",
    usage: "Recover the linear comparison EOM away from turning points, and extend by continuity. The full-trig energy derivative uses its trigonometric restoring term.",
    sources: ["IMG_5917.HEIC", "IMG_5919.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["chain rule", "derivative", "energy method"],
  },
  {
    id: "pend-lagrange-kinetic",
    title: "Lagrange kinetic-energy derivatives",
    scope: "pendulum",
    group: "Energy and Lagrange derivation",
    tex: [
      String.raw`\frac{\partial T}{\partial\dot\theta}=J_O\dot\theta`,
      String.raw`\frac{d}{dt}\left(\frac{\partial T}{\partial\dot\theta}\right)=J_O\ddot\theta`,
      String.raw`\frac{\partial T}{\partial\theta}=0`,
    ],
    description: "Treat theta and theta-dot as independent variables when taking partial derivatives. J_O is constant.",
    usage: "These inertial derivatives apply to both the linear and full-trig pendulum modes.",
    sources: ["IMG_5917.HEIC", "IMG_5920.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["partial derivative", "Lagrange", "kinetic"],
  },
  {
    id: "pend-lagrange-geometric",
    title: "Full-trig potential and its derivative",
    scope: "pendulum",
    group: "Energy and Lagrange derivation",
    tex: [
      String.raw`U_{\mathrm{geometry}}=mgL(1-\cos\theta)+\tfrac12kL^2\sin^2\theta`,
      String.raw`\frac{\partial U_{\mathrm{geometry}}}{\partial\theta}=mgL\sin\theta+kL^2\sin\theta\cos\theta`,
    ],
    description: "Differentiate sin-squared theta using the chain rule: its derivative is 2 sin(theta) cos(theta). This potential matches the ideal horizontal spring in the lecture.",
    usage: "This gives the exact restoring term used in full-trig mode and in its energy traces, within the stated spring idealization.",
    sources: ["IMG_5917.HEIC", "IMG_5918.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["chain rule", "sin squared", "Lagrange", "derivation"],
  },
  {
    id: "pend-lagrange-linear",
    title: "Linear comparison: potential derivative and EOM",
    scope: "pendulum",
    group: "Energy and Lagrange derivation",
    tex: [
      String.raw`\frac{\partial U}{\partial\theta}=\frac{\partial}{\partial\theta}\left(\tfrac12K_\theta\theta^2\right)=K_\theta\theta`,
      String.raw`\frac{d}{dt}\left(\frac{\partial T}{\partial\dot\theta}\right)-\frac{\partial T}{\partial\theta}+\frac{\partial U}{\partial\theta}=0`,
      String.raw`J_O\ddot\theta+K_\theta\theta=0`,
    ],
    description: "Substitute the kinetic and potential derivatives into the unforced Euler-Lagrange equation.",
    usage: "These derivatives independently recover the small-angle comparison equation.",
    sources: ["IMG_5917.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["Lagrange", "partial derivative", "EOM"],
  },
  {
    id: "pend-frequency-limits",
    title: "Small-angle frequency checks in two limiting cases",
    scope: "pendulum",
    group: "Equation of motion and natural frequency",
    tex: [
      String.raw`k=0:\quad\omega_n=\sqrt{g/L}`,
      String.raw`g=0:\quad\omega_n=\sqrt{k/m}`,
    ],
    description: "Removing the spring leaves a simple small-angle pendulum. Removing gravity leaves a spring-controlled oscillator.",
    usage: "These checks concern the linearized frequency. Finite-angle full-trig periods can depend on the release amplitude.",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["limits", "simple pendulum", "sanity check"],
  },
  {
    id: "mechanics-rotational-newton",
    title: "Rotational Newton law and angular derivatives",
    scope: "shared",
    group: "Motion and forces",
    tex: [
      String.raw`\sum M_O=J_O\ddot\theta`,
      String.raw`\dot\theta=\frac{d\theta}{dt},\qquad\ddot\theta=\frac{d^2\theta}{dt^2}`,
    ],
    description: "About a fixed rotation axis, net torque equals mass moment of inertia times angular acceleration.",
    usage: "This is the rotational counterpart of sum F=m x-double-dot.",
    sources: ["IMG_5914.HEIC", "IMG_5922.HEIC"],
    tags: ["Newton", "torque", "angular acceleration"],
  },
  {
    id: "mechanics-mass-inertia",
    title: "Mass moment of inertia about an axis",
    scope: "shared",
    group: "Inertia and units",
    tex: [
      String.raw`J_O=\int r_\perp^2\,dm`,
      String.raw`[J_O]=\mathrm{kg\,m^2}`,
      String.raw`\text{point mass at radius }L:\quad J_O=mL^2`,
    ],
    description: "r_perp is perpendicular distance to the rotation axis. Mass moment describes resistance to angular acceleration.",
    usage: "Use this inertia in an angular EOM; do not substitute an area second moment.",
    sources: ["IMG_5922.HEIC", "IMG_5921.HEIC"],
    correction: "The source’s phrase about J resisting torsion is imprecise. Rotational inertia governs acceleration; torsional stiffness governs elastic twist.",
    tags: ["inertia", "mass", "J"],
  },
  {
    id: "mechanics-conservation",
    title: "Conserved mechanical energy uses T plus U",
    scope: "shared",
    group: "Energy",
    tex: [
      String.raw`E=T+U=\mathrm{constant}`,
      String.raw`\frac{d}{dt}(T+U)=0`,
    ],
    description: "T is kinetic energy and U is potential energy. This conservation statement applies to the unforced, undamped models.",
    usage: "Use the plus sign when checking the total-energy plot. The Lagrangian T-U is a different quantity.",
    sources: ["IMG_5917.HEIC", "IMG_5919.HEIC"],
    correction: "IMG_5919 writes d(T-U)/dt=0 in its first handwritten box. That sign is incorrect; the later derivation on the same page and IMG_5917 correctly use d(T+U)/dt=0.",
    tags: ["energy", "source correction", "conservation"],
  },
  {
    id: "mechanics-energy-pairs",
    title: "Translation and rotation energy pairs",
    scope: "shared",
    group: "Energy",
    tex: [
      String.raw`T_{\mathrm{translation}}=\tfrac12m\dot x^2,\qquad U_{\mathrm{linear\ spring}}=\tfrac12kx^2`,
      String.raw`T_{\mathrm{rotation}}=\tfrac12J\dot\theta^2,\qquad U_{\mathrm{torsion}}=\tfrac12k_t\theta^2`,
    ],
    description: "Choose the coordinate, inertia and stiffness consistently. Linear stiffness is N/m; torsional stiffness is N m/rad.",
    usage: "The network uses the translation pair with k_eq. The linear pendulum uses the rotational pair with K_theta; full-trig pendulum potential is given by separate trigonometric expressions.",
    sources: ["IMG_5917.HEIC"],
    tags: ["energy", "translation", "rotation"],
  },
  {
    id: "mechanics-gravity-potential",
    title: "Gravitational potential relative to a datum",
    scope: "shared",
    group: "Energy",
    tex: [
      String.raw`U_g=mgh`,
    ],
    description: "h is center-of-mass height above a chosen reference level. An additive constant in potential does not change the force or EOM.",
    usage: "Choose a convenient datum; the pendulum uses its lowest bob position. The network’s gravity is absorbed into its loaded-equilibrium coordinate.",
    sources: ["IMG_5918.HEIC"],
    tags: ["gravity", "height", "datum"],
  },
  {
    id: "mechanics-lagrangian",
    title: "Lagrangian definition and general equation",
    scope: "lecture",
    group: "Energy and Lagrange reference",
    tex: [
      String.raw`\mathcal L(q_i,\dot q_i,t)=T-U`,
      String.raw`\frac{d}{dt}\left(\frac{\partial\mathcal L}{\partial\dot q_i}\right)-\frac{\partial\mathcal L}{\partial q_i}=0`,
      String.raw`\frac{d}{dt}\left(\frac{\partial T}{\partial\dot q_i}\right)-\frac{\partial T}{\partial q_i}+\frac{\partial U}{\partial q_i}=0`,
    ],
    description: "The last form assumes U has no generalized-velocity dependence. The zero right-hand side represents no nonconservative generalized force.",
    usage: "Use the method as an alternative derivation, with q=theta for pendulum or q=x for network.",
    sources: ["IMG_5917.HEIC"],
    tags: ["Lagrange", "reference", "generalized coordinate"],
  },
  {
    id: "mechanics-spring-lagrange",
    title: "Lagrange derivatives for a translating spring–mass system",
    scope: "lecture",
    group: "Energy and Lagrange reference",
    tex: [
      String.raw`T=\tfrac12m\dot x^2,\quad U=\tfrac12kx^2`,
      String.raw`\frac{\partial T}{\partial\dot x}=m\dot x,\quad\frac{d}{dt}\left(\frac{\partial T}{\partial\dot x}\right)=m\ddot x`,
      String.raw`\frac{\partial T}{\partial x}=0,\quad\frac{\partial U}{\partial x}=kx`,
      String.raw`m\ddot x+kx=0`,
    ],
    description: "This is Topic 03 Practice Problem 1. The same derivation applies to the active network after spring reduction.",
    usage: "For the network substitute k_eq for k.",
    sources: ["IMG_5919.HEIC"],
    tags: ["Lagrange", "partial derivative", "spring mass"],
  },
  {
    id: "mechanics-shaft-oscillator",
    title: "Shaft-and-disk torsional reference",
    scope: "lecture",
    group: "Torsional oscillator reference",
    tex: [
      String.raw`J\ddot\theta+k_t\theta=0`,
      String.raw`\theta(t)=A\sin(\omega_nt+\phi)`,
      String.raw`\omega_n=\sqrt{k_t/J},\quad f_n=\frac1{2\pi}\sqrt{k_t/J},\quad T_n=2\pi\sqrt{J/k_t}`,
    ],
    description: "A torsionally elastic shaft restores a disk toward its untwisted position. This is a separate lecture model.",
    usage: "The linear pendulum comparison has this form with stiffness mgL+kL^2. Full-trig pendulum restoring torque is nonlinear.",
    sources: ["IMG_5914.HEIC", "IMG_5915.HEIC", "IMG_5916.HEIC"],
    tags: ["shaft", "torsion", "background"],
  },
  {
    id: "mechanics-rod-heights",
    title: "Uniform-rod centroid heights",
    scope: "lecture",
    group: "Other pendulum models",
    tex: [
      String.raw`h_{\mathrm{hanging}}=\frac L2(1-\cos\theta)`,
      String.raw`h_{\mathrm{inverted}}=\frac L2\cos\theta`,
    ],
    description: "A uniform rod’s center of mass lies halfway along its length. These formulas use different reference levels.",
    usage: "These are rod examples; do not use L/2 for the active massless-rod, point-bob model.",
    sources: ["IMG_5918.HEIC"],
    tags: ["rod", "centroid", "background"],
  },
  {
    id: "mechanics-inverted-energy",
    title: "Inverted uniform bar: kinetic and potential energy",
    scope: "lecture",
    group: "Inverted pendulum · reference",
    tex: [
      String.raw`T=\tfrac12J_O\dot\theta^2`,
      String.raw`U=\tfrac12k_t\theta^2+mg\frac L2\cos\theta`,
    ],
    description: "The uniform bar is upright at theta=0 and has a torsion spring at its lower pivot. J_O is given about that pivot.",
    usage: "This Topic 03 example is not the active hanging pendulum.",
    sources: ["IMG_5920.HEIC"],
    tags: ["inverted", "energy", "background"],
  },
  {
    id: "mechanics-inverted-derivatives",
    title: "Inverted bar: Lagrange derivative steps",
    scope: "lecture",
    group: "Inverted pendulum · reference",
    tex: [
      String.raw`\frac{\partial T}{\partial\dot\theta}=J_O\dot\theta,\quad\frac{d}{dt}\left(\frac{\partial T}{\partial\dot\theta}\right)=J_O\ddot\theta,\quad\frac{\partial T}{\partial\theta}=0`,
      String.raw`\frac{\partial U}{\partial\theta}=k_t\theta-\frac{mgL}{2}\sin\theta`,
    ],
    description: "Differentiate cosine to negative sine. Gravity therefore reduces the restoring moment about the upright equilibrium.",
    usage: "This sign is opposite to gravity’s restoring role in the active hanging pendulum.",
    sources: ["IMG_5920.HEIC"],
    tags: ["inverted", "Lagrange", "derivative"],
  },
  {
    id: "mechanics-inverted-eom",
    title: "Inverted bar: nonlinear and linearized EOM",
    scope: "lecture",
    group: "Inverted pendulum · reference",
    tex: [
      String.raw`J_O\ddot\theta+k_t\theta-\frac{mgL}{2}\sin\theta=0`,
      String.raw`J_O\ddot\theta+\left(k_t-\frac{mgL}{2}\right)\theta=0`,
    ],
    description: "Using sin(theta) approximately theta gives the linearized upright model.",
    usage: "The active hanging model adds the gravity stiffness; this upright model subtracts it.",
    sources: ["IMG_5920.HEIC"],
    tags: ["inverted", "EOM", "linearization"],
  },
  {
    id: "mechanics-inverted-frequency",
    title: "Inverted bar: frequency and stability condition",
    scope: "lecture",
    group: "Inverted pendulum · reference",
    tex: [
      String.raw`K_{\mathrm{eff}}=k_t-\frac{mgL}{2}`,
      String.raw`\omega_n=\sqrt{\frac{k_t-mgL/2}{J_O}},\quad T_n=\frac{2\pi}{\omega_n}`,
      String.raw`K_{\mathrm{eff}}>0\ \Longleftrightarrow\ k_t>mgL/2`,
    ],
    description: "A real oscillatory natural frequency requires positive effective stiffness. Zero stiffness is marginal in the linear model; negative stiffness is unstable.",
    usage: "The stability condition is a derived qualification on the lecture’s frequency formula.",
    sources: ["IMG_5920.HEIC"],
    reconstructed: true,
    tags: ["stability", "inverted", "frequency"],
  },
  {
    id: "mechanics-area-inertia",
    title: "Area second moment and bending stress",
    scope: "lecture",
    group: "Inertia and units",
    tex: [
      String.raw`I_x=\int_A r_\perp^2\,dA,\qquad[I_x]=\mathrm{m^4}`,
      String.raw`\sigma=\frac{My}{I}`,
    ],
    description: "Area second moment is a cross-section property. Bending stress also depends on moment and distance from the neutral axis.",
    usage: "This is structural background; the active pendulum inertia J=mL^2 has different units and physical meaning.",
    sources: ["IMG_5922.HEIC"],
    correction: "The photo’s bending-axis subscripts are inconsistent, so the standard unindexed stress relation is shown. I is not mass moment of inertia.",
    tags: ["area moment", "bending", "units", "background"],
  },
  {
    id: "mechanics-ode-classification",
    title: "Linear, homogeneous ODE classification",
    scope: "lecture",
    group: "Differential equations reference",
    tex: [
      String.raw`a y^{\prime\prime}+b y^\prime+cy=f(x)`,
      String.raw`f(x)=0:\ \text{homogeneous};\qquad f(x)\ne0:\ \text{nonhomogeneous}`,
    ],
    description: "Linearity requires the dependent variable and its derivatives to occur linearly, without products or nonlinear functions of them. Two initial conditions specify a second-order initial-value problem.",
    usage: "The spring network and linear pendulum comparison are linear homogeneous ODEs. The active full-trig pendulum is a nonlinear unforced ODE.",
    sources: ["IMG_5911.HEIC", "IMG_5912.HEIC"],
    tags: ["ODE", "homogeneous", "linear"],
  },
  {
    id: "mechanics-ode-examples",
    title: "Linear versus nonlinear examples",
    scope: "lecture",
    group: "Differential equations reference",
    tex: [
      String.raw`\ddot x+x=0\quad\text{linear}`,
      String.raw`\ddot x+1/x=0\quad\text{nonlinear}`,
      String.raw`\ddot x+\cos x=0\quad\text{nonlinear}`,
    ],
    description: "The final two examples are background equations, not either simulation.",
    usage: "The exact trigonometric pendulum restoring terms are nonlinear in theta; their first-order approximation produces the linear comparison.",
    sources: ["IMG_5911.HEIC"],
    tags: ["ODE", "nonlinear", "background"],
  },
  {
    id: "mechanics-ode-roots",
    title: "General constant-coefficient characteristic roots",
    scope: "lecture",
    group: "Differential equations reference",
    tex: [
      String.raw`y=e^{rx}\ \Longrightarrow\ ar^2+br+c=0`,
      String.raw`\Delta=b^2-4ac`,
      String.raw`\Delta>0:\quad y=C_1e^{r_1x}+C_2e^{r_2x}`,
      String.raw`\Delta=0:\quad y=e^{rx}(C_1+C_2x)`,
      String.raw`\Delta<0,\ r=p\pm iq:\quad y=e^{px}(C_1\cos qx+C_2\sin qx)`,
    ],
    description: "The root symbol r is used instead of the sheet’s m to avoid confusing it with physical mass. Undamped oscillation has p=0.",
    usage: "The real/repeated-root cases are mathematical background. They do not mean damping is active in these simulations.",
    sources: ["IMG_5912.HEIC"],
    tags: ["characteristic", "roots", "ODE", "background"],
  },
  {
    id: "mechanics-trig-reciprocal",
    title: "Reciprocal and quotient identities",
    scope: "lecture",
    group: "Trigonometric identities reference",
    tex: [
      String.raw`\sin u=\frac1{\csc u},\quad\cos u=\frac1{\sec u},\quad\tan u=\frac1{\cot u}`,
      String.raw`\tan u=\frac{\sin u}{\cos u},\quad\cot u=\frac{\cos u}{\sin u}`,
    ],
    description: "These supporting identities apply wherever their denominators exist.",
    usage: "Useful for manipulating angles; the live evaluator uses sine and cosine directly.",
    sources: ["IMG_5913.HEIC"],
    tags: ["trigonometry", "quotient", "reciprocal"],
  },
  {
    id: "mechanics-trig-other-pythagorean",
    title: "Tangent and cotangent Pythagorean identities",
    scope: "lecture",
    group: "Trigonometric identities reference",
    tex: [
      String.raw`1+\tan^2u=\sec^2u`,
      String.raw`1+\cot^2u=\csc^2u`,
    ],
    description: "These follow from sin-squared plus cos-squared equals one by division.",
    usage: "Supporting lecture reference; valid only where the relevant quotient functions are defined.",
    sources: ["IMG_5913.HEIC"],
    tags: ["trigonometry", "Pythagorean"],
  },
  {
    id: "mechanics-trig-tangent",
    title: "Tangent angle addition and odd symmetry",
    scope: "lecture",
    group: "Trigonometric identities reference",
    tex: [
      String.raw`\tan(\alpha\pm\beta)=\frac{\tan\alpha\pm\tan\beta}{1\mp\tan\alpha\tan\beta}`,
      String.raw`\tan(-u)=-\tan u`,
    ],
    description: "Use opposite signs in the denominator and numerator. The quotient must be defined.",
    usage: "Supporting angle manipulation; not needed for evaluating the active response.",
    sources: ["IMG_5913.HEIC"],
    tags: ["trigonometry", "angle addition", "tangent"],
  },
  {
    id: "mechanics-trig-double",
    title: "Double-angle identities",
    scope: "lecture",
    group: "Trigonometric identities reference",
    tex: [
      String.raw`\sin 2u=2\sin u\cos u`,
      String.raw`\cos 2u=\cos^2u-\sin^2u=2\cos^2u-1=1-2\sin^2u`,
      String.raw`\tan 2u=\frac{2\tan u}{1-\tan^2u}`,
    ],
    description: "These identities rewrite products or squared trigonometric terms.",
    usage: "For example, the pre-linearized spring torque contains sin(theta) cos(theta).",
    sources: ["IMG_5913.HEIC"],
    tags: ["trigonometry", "double angle"],
  },
  {
    id: "mechanics-trig-cofunction",
    title: "Cofunction identities with the corrected cotangent sign",
    scope: "lecture",
    group: "Trigonometric identities reference",
    tex: [
      String.raw`\sin(\pi/2-u)=\sin(\pi/2+u)=\cos u`,
      String.raw`\cos(\pi/2-u)=\sin u,\quad\cos(\pi/2+u)=-\sin u`,
      String.raw`\tan(\pi/2-u)=\cot u,\quad\cot(\pi/2-u)=\tan u`,
      String.raw`\cot(\pi/2+u)=-\tan u`,
      String.raw`\sec(\pi/2-u)=\csc u,\quad\csc(\pi/2-u)=\sec u`,
    ],
    description: "The photo uses 90 degrees. These equivalent forms use radians, as required for differentiation without conversion factors.",
    usage: "Use the denominator restrictions of secant, cosecant, tangent and cotangent.",
    sources: ["IMG_5913.HEIC"],
    correction: "The printed cot(90 degrees + theta) = -cot(theta) is incorrect. The correct identity is cot(90 degrees + theta) = -tan(theta).",
    tags: ["trigonometry", "cofunction", "source correction"],
  },
  {
    id: "pend-trig-state",
    title: "Full-trig initial-value equation",
    scope: "pendulum",
    group: "Full-trig motion",
    tex: [
      String.raw`\dot\theta=\Omega`,
      String.raw`\dot\Omega=-\frac gL\sin\theta-\frac km\sin\theta\cos\theta`,
      String.raw`\theta(0)=\theta_0,\qquad\Omega(0)=\dot\theta_0`,
    ],
    description: "Divide the torque equation by mL squared to obtain angular acceleration. Omega denotes the instantaneous angular velocity, not natural frequency.",
    usage: "This first-order state system evolves the selected full-trig trajectory.",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["nonlinear", "initial conditions", "angular acceleration"],
  },
  {
    id: "pend-trig-kinematics",
    title: "Full-trig position, velocity, and acceleration",
    scope: "pendulum",
    group: "Full-trig motion",
    tex: [
      String.raw`x=L\sin\theta`,
      String.raw`v_x=\dot x=L\cos\theta\,\dot\theta`,
      String.raw`a_x=\ddot x=L\left(\cos\theta\,\ddot\theta-\sin\theta\,\dot\theta^2\right)`,
      String.raw`z_{\mathrm{down}}=L\cos\theta,\quad v_z=-L\sin\theta\,\dot\theta`,
      String.raw`a_z=-L\left(\cos\theta\,\dot\theta^2+\sin\theta\,\ddot\theta\right)`,
    ],
    description: "Differentiate the geometric projections using the chain and product rules. The theta-dot squared terms arise from the changing direction of motion.",
    usage: "Full-trig horizontal readouts require these derivatives; x=L theta and v=L theta-dot apply only to the linear comparison.",
    sources: ["IMG_5921.HEIC", "IMG_5919.HEIC"],
    reconstructed: true,
    tags: ["nonlinear", "chain rule", "product rule", "velocity", "acceleration"],
  },
  {
    id: "pend-trig-bob-speed",
    title: "Total bob speed versus horizontal velocity",
    scope: "pendulum",
    group: "Full-trig motion",
    tex: [
      String.raw`v_{\mathrm{bob}}^2=v_x^2+v_z^2=L^2\dot\theta^2`,
      String.raw`\sin^2\theta+\cos^2\theta=1`,
    ],
    description: "Circular motion has both horizontal and vertical velocity components. Their squares add to the squared tangential speed.",
    usage: "This identity explains why the rotational kinetic energy remains one-half m L-squared theta-dot-squared at finite angle.",
    sources: ["IMG_5921.HEIC", "IMG_5913.HEIC"],
    reconstructed: true,
    tags: ["speed", "kinetic energy", "Pythagorean"],
  },
  {
    id: "pend-trig-energy",
    title: "Full-trig energy ledger",
    scope: "pendulum",
    group: "Energy",
    tex: [
      String.raw`T=\tfrac12mL^2\dot\theta^2`,
      String.raw`U_g=mgL(1-\cos\theta)`,
      String.raw`U_s=\tfrac12kL^2\sin^2\theta`,
      String.raw`E=T+U_g+U_s=E_0`,
    ],
    description: "These energies are consistent with the full-trig torque equation and its ideal horizontal spring.",
    usage: "Use exact trigonometric potential energy in full-trig mode. Energy stays constant in the ideal model; numerical evolution may have small integration error.",
    sources: ["IMG_5917.HEIC", "IMG_5918.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["nonlinear", "energy", "conservation"],
  },
  {
    id: "pend-trig-energy-derivative",
    title: "Full-trig energy differentiation recovers the EOM",
    scope: "pendulum",
    group: "Energy and Lagrange derivation",
    tex: [
      String.raw`\frac{dE}{dt}=\dot\theta\left[mL^2\ddot\theta+mgL\sin\theta+kL^2\sin\theta\cos\theta\right]=0`,
      String.raw`\frac{\partial U}{\partial\theta}=mgL\sin\theta+kL^2\sin\theta\cos\theta`,
    ],
    description: "The restoring torque is the negative derivative of potential with respect to theta.",
    usage: "This connects the energy ledger, Lagrange derivation, and live full-trig torque balance.",
    sources: ["IMG_5917.HEIC", "IMG_5918.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["nonlinear", "energy method", "Lagrange", "chain rule"],
  },
  {
    id: "pend-trig-residual",
    title: "Full-trig equation balance",
    scope: "pendulum",
    group: "Force and torque",
    tex: [
      String.raw`R_{\mathrm{trig}}=mL^2\ddot\theta+mgL\sin\theta+kL^2\sin\theta\cos\theta`,
      String.raw`R_{\mathrm{trig}}=0`,
    ],
    description: "The inertial and trigonometric restoring terms must cancel at every physical sample.",
    usage: "This residual checks instantaneous equation consistency. Energy drift is a separate numerical-trajectory check.",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["nonlinear", "residual", "verification"],
  },
  {
    id: "pend-trig-turning-angle",
    title: "Full-trig amplitude follows potential energy",
    scope: "pendulum",
    group: "Full-trig motion",
    tex: [
      String.raw`E_0=\tfrac12mL^2\dot\theta_0^2+mgL(1-\cos\theta_0)+\tfrac12kL^2\sin^2\theta_0`,
      String.raw`\dot\theta=0\ \Longrightarrow\ U(\theta_{\mathrm{turn}})=E_0`,
    ],
    description: "Turning angles are found where kinetic energy vanishes. The linear square-root amplitude formula is generally not exact at finite angle.",
    usage: "Choose the turning point in the same accessible potential well; a real oscillatory turning point is required.",
    sources: ["IMG_5917.HEIC", "IMG_5918.HEIC", "IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["nonlinear", "amplitude", "turning point", "energy"],
  },
  {
    id: "pend-trig-force-readouts",
    title: "Full-trig horizontal net force and tangential force",
    scope: "pendulum",
    group: "Force and torque",
    tex: [
      String.raw`F_{s,x}=-kL\sin\theta`,
      String.raw`F_{\mathrm{net},x}=ma_x=mL\left(\cos\theta\,\ddot\theta-\sin\theta\,\dot\theta^2\right)`,
      String.raw`F_{\mathrm{tangent}}=\frac{M_g+M_s}{L}=-mg\sin\theta-kL\sin\theta\cos\theta`,
    ],
    description: "The net horizontal force includes the rod’s constraint force. Torque divided by L is a tangential generalized force, which is a different quantity.",
    usage: "The full-trig net-force readout uses m times horizontal acceleration. Keep it separate from the horizontal spring force and tangential force.",
    sources: ["IMG_5921.HEIC"],
    reconstructed: true,
    tags: ["nonlinear", "net force", "constraint", "tangent", "readout"],
  },
  {
    id: "pend-trig-period",
    title: "Full-trig period from the energy integral",
    scope: "pendulum",
    group: "Full-trig motion",
    tex: [
      String.raw`\dot\theta^2=\frac{2[E_0-U(\theta)]}{J_O}`,
      String.raw`T_{\mathrm{osc}}=4\int_0^A\sqrt{\frac{J_O}{2[E_0-U(\theta)]}}\,d\theta`,
      String.raw`f_{\mathrm{osc}}=\frac1{T_{\mathrm{osc}}},\qquad\omega_{\mathrm{osc}}=\frac{2\pi}{T_{\mathrm{osc}}}`,
    ],
    description: "For libration in the symmetric well about theta=0, A is the positive turning angle and U(A)=E_0. Four quarter-cycle travel times give the full period.",
    usage: "Full-trig period and frequency depend on energy and amplitude. The separately reported small-angle reference omega_n=sqrt(g/L+k/m) is not generally 2 pi divided by this finite-amplitude period.",
    sources: ["IMG_5917.HEIC", "IMG_5918.HEIC", "IMG_5921.HEIC", "src/physics/model.ts"],
    reconstructed: true,
    tags: ["nonlinear", "period", "quadrature", "energy", "frequency"],
  },
  {
    id: "pend-trig-scaled-potential",
    title: "Potential per unit rotational inertia",
    scope: "pendulum",
    group: "Numerical evaluation",
    tex: [
      String.raw`a=\frac gL,\qquad b=\frac km,\qquad \mathcal V(\theta)=\frac{U(\theta)}{J_O}`,
      String.raw`\mathcal V(\theta)=2a\sin^2(\theta/2)+\tfrac12b\sin^2\theta`,
      String.raw`\varepsilon=\frac{E_0}{J_O}=\tfrac12\dot\theta_0^2+\mathcal V(\theta_0)`,
      String.raw`1-\cos\theta=2\sin^2(\theta/2)`,
    ],
    description: "The code divides energy by the constant inertia. The half-angle form avoids subtracting nearly equal numbers at small angles. Here a and b are frequency-squared coefficients, not acceleration.",
    usage: "These scaled energies give the same turning points and period as the dimensional energies. Units of epsilon and V are inverse seconds squared.",
    sources: ["IMG_5917.HEIC", "IMG_5918.HEIC", "IMG_5921.HEIC", "src/physics/model.ts"],
    reconstructed: true,
    tags: ["numerical", "half angle", "energy", "units"],
  },
  {
    id: "pend-trig-amplitude-root",
    title: "Stable turning-amplitude formula",
    scope: "pendulum",
    group: "Numerical evaluation",
    tex: [
      String.raw`s_A=\sin(A/2),\qquad \varepsilon=2s_A^2(a+b-bs_A^2)`,
      String.raw`s_A^2=\frac{\varepsilon}{a+b+\sqrt{(a+b)^2-2b\varepsilon}}`,
      String.raw`A=2\arcsin(s_A)`,
    ],
    description: "Solving the energy equation gives the positive turning point in the well around theta=0. Rationalizing the quadratic root avoids numerical cancellation as the amplitude approaches zero.",
    usage: "This computes bounded full-trig amplitude when the initial angular rate is nonzero. For a release from rest inside this well, A equals the absolute starting angle.",
    sources: ["IMG_5917.HEIC", "IMG_5921.HEIC", "src/physics/model.ts"],
    reconstructed: true,
    tags: ["numerical", "amplitude", "quadratic", "turning point"],
  },
  {
    id: "pend-trig-period-transform",
    title: "Half-angle transformation used for the period",
    scope: "pendulum",
    group: "Numerical evaluation",
    tex: [
      String.raw`\sin(\theta/2)=s_A\sin\phi,\qquad s_A=\sin(A/2)`,
      String.raw`\frac{d\theta}{d\phi}=\frac{2s_A\cos\phi}{\sqrt{1-s_A^2\sin^2\phi}}`,
      String.raw`T_{\mathrm{osc}}=4\int_0^{\pi/2}\frac{d\phi}{\sqrt{(1-s_A^2\sin^2\phi)\,[a+b(1-s_A^2(1+\sin^2\phi))]}}`,
    ],
    description: "The substitution cancels the turning-point singularity of the original energy integral. It applies to an oscillation within the well about zero, below the barrier energy.",
    usage: "The implementation integrates this smooth expression to obtain the finite-amplitude period. As A tends to zero it reduces to 2 pi divided by sqrt(a+b).",
    sources: ["IMG_5917.HEIC", "IMG_5918.HEIC", "IMG_5921.HEIC", "src/physics/model.ts"],
    reconstructed: true,
    tags: ["quadrature", "numerical", "chain rule", "period", "half angle"],
  },
  {
    id: "pend-trig-regimes",
    title: "Oscillation, rotation, and the separating energy",
    scope: "pendulum",
    group: "Numerical evaluation",
    tex: [
      String.raw`\theta_b=\begin{cases}\arccos(-a/b),&b>a,\\\pi,&b\le a,\end{cases}\qquad \varepsilon_b=\mathcal V(\theta_b)`,
      String.raw`\varepsilon<\varepsilon_b:\ \text{libration in the well about zero}`,
      String.raw`\varepsilon>\varepsilon_b:\ \text{continuous rotation}`,
      String.raw`\varepsilon=\varepsilon_b:\ \text{separatrix, no finite cycle}`,
      String.raw`T_{\mathrm{rotation}}=\int_0^{2\pi}\frac{d\theta}{\sqrt{2[\varepsilon-\mathcal V(\theta)]}}`,
    ],
    description: "The maximum accessible potential separates bounded swinging from rotation. The rotation integral gives the time to advance by one full turn. The exact barrier trajectory approaches unstable equilibrium asymptotically.",
    usage: "The app’s release-from-rest controls within 60 degrees stay in the bounded regime. These formulas also protect direct callers that supply a nonzero initial angular rate.",
    sources: ["IMG_5917.HEIC", "IMG_5921.HEIC", "src/physics/model.ts"],
    reconstructed: true,
    tags: ["numerical", "rotation", "separatrix", "energy barrier", "stability"],
  },
  {
    id: "pend-trig-rk4",
    title: "Fourth-order Runge–Kutta evolution",
    scope: "pendulum",
    group: "Numerical evaluation",
    tex: [
      String.raw`\mathbf y=\begin{bmatrix}\theta\\\Omega\end{bmatrix},\qquad \mathbf F(\mathbf y)=\begin{bmatrix}\Omega\\-a\sin\theta-b\sin\theta\cos\theta\end{bmatrix}`,
      String.raw`\mathbf K_1=\mathbf F(\mathbf y_n),\quad\mathbf K_2=\mathbf F(\mathbf y_n+\tfrac h2\mathbf K_1)`,
      String.raw`\mathbf K_3=\mathbf F(\mathbf y_n+\tfrac h2\mathbf K_2),\quad\mathbf K_4=\mathbf F(\mathbf y_n+h\mathbf K_3)`,
      String.raw`\mathbf y_{n+1}=\mathbf y_n+\frac h6(\mathbf K_1+2\mathbf K_2+2\mathbf K_3+\mathbf K_4)`,
    ],
    description: "Four evaluations of the same nonlinear acceleration advance angle and angular velocity by time step h. K here denotes numerical slopes, not spring stiffness.",
    usage: "The implementation precomputes a cycle on a fixed physical-time grid. Playback speed changes how quickly that physical time is displayed; it does not change the torque law.",
    sources: ["IMG_5921.HEIC", "src/physics/model.ts"],
    reconstructed: true,
    tags: ["numerical", "Runge Kutta", "RK4", "integration", "time step"],
  },
  {
    id: "pend-trig-hermite",
    title: "Smooth states between computed time samples",
    scope: "pendulum",
    group: "Numerical evaluation",
    tex: [
      String.raw`s=\frac{t-t_n}{h},\qquad 0\le s\le1`,
      String.raw`\theta(s)=H_{00}(s)\theta_n+hH_{10}(s)\Omega_n+H_{01}(s)\theta_{n+1}+hH_{11}(s)\Omega_{n+1}`,
      String.raw`H_{00}=2s^3-3s^2+1,\quad H_{10}=s^3-2s^2+s`,
      String.raw`H_{01}=-2s^3+3s^2,\quad H_{11}=s^3-s^2`,
      String.raw`\Omega(s)=\frac1h\frac{d\theta(s)}{ds}`,
    ],
    description: "Cubic Hermite interpolation matches both angle and angular velocity at each end of the small time interval. Differentiating the interpolated angle gives its rate.",
    usage: "This provides smooth motion and repeatable time scrubbing between RK4 samples. Angular acceleration is then evaluated from the nonlinear torque law.",
    sources: ["IMG_5921.HEIC", "src/physics/model.ts"],
    reconstructed: true,
    tags: ["numerical", "Hermite", "interpolation", "derivative", "scrubbing"],
  },
  {
    id: "pend-trig-simpson",
    title: "Adaptive Simpson integration for the period",
    scope: "pendulum",
    group: "Numerical evaluation",
    tex: [
      String.raw`S(\alpha,\beta)=\frac{\beta-\alpha}{6}\left[f(\alpha)+4f\!\left(\frac{\alpha+\beta}{2}\right)+f(\beta)\right]`,
      String.raw`S_2=S(\alpha,c)+S(c,\beta),\qquad c=\frac{\alpha+\beta}{2}`,
      String.raw`\Delta=S_2-S(\alpha,\beta),\qquad I\approx S_2+\frac{\Delta}{15}`,
      String.raw`|\Delta|\le15\,\mathrm{tol}\quad\text{accept; otherwise subdivide}`,
    ],
    description: "The period integral is estimated on an interval and its two halves. Their difference provides an error estimate; smaller intervals are used where needed.",
    usage: "The implementation applies this quadrature to the smooth period integrand. This is a numerical method added for the simulation, not a handwritten lecture formula.",
    sources: ["IMG_5921.HEIC", "src/physics/model.ts"],
    reconstructed: true,
    tags: ["numerical", "Simpson", "quadrature", "period", "tolerance"],
  },
]
