import type { FormulaEntry } from './formulaTypes'

/** Zero-inertia constraints derived from the same force balances as the live models. */
export const masslessFormulas: FormulaEntry[] = [
  {
    id: 'massless-inertia-constraint',
    title: 'Exactly zero mass gives a constraint',
    scope: 'shared',
    group: 'Zero-mass limit',
    tex: [
      String.raw`M\ddot q+R(q)=0`,
      String.raw`M=0\quad\Longrightarrow\quad R(q)=0`,
      String.raw`\omega_n=\sqrt{K/M}\quad\text{requires }M>0`,
    ],
    description: 'With no inertia, the equation cannot determine acceleration by dividing by mass. It instead requires the remaining forces or torques to balance.',
    usage: 'The zero-mass setting displays a static constraint state with no oscillatory period or natural frequency. A displaced release is not a compatible free initial condition for that constraint.',
    sources: ['src/physics/model.ts'],
    reconstructed: true,
    tags: ['zero mass', 'massless', 'inertia', 'constraint', 'frequency'],
  },
  {
    id: 'massless-positive-limit',
    title: 'A limit is different from setting mass to zero',
    scope: 'shared',
    group: 'Zero-mass limit',
    tex: [
      String.raw`K>0:\quad\lim_{M\to0^+}\sqrt{K/M}=+\infty`,
      String.raw`M=0:\quad Kq=0`,
    ],
    description: 'For positive inertia approaching zero with fixed positive stiffness, the linear frequency grows without bound. At exactly zero inertia, the differential equation changes into an algebraic constraint.',
    usage: 'Do not interpret the 0 kg setting as an infinitely fast animation or evaluate a division by zero. The pendulum also has a special case when both mass and spring stiffness vanish.',
    sources: ['src/physics/model.ts'],
    reconstructed: true,
    tags: ['zero mass', 'limit', 'singular limit', 'frequency'],
  },
  {
    id: 'massless-network',
    title: 'Zero-mass spring network: equilibrium only',
    scope: 'network',
    group: 'Zero-mass limit',
    tex: [
      String.raw`m\ddot x+k_{\mathrm{eq}}x=0`,
      String.raw`m=0:\quad k_{\mathrm{eq}}x=0`,
      String.raw`k_{\mathrm{eq}}>0\quad\Longrightarrow\quad x=0`,
    ],
    description: 'The allowed spring stiffnesses make the equivalent stiffness positive. Without the moving mass, the spring-force balance fixes its displacement at equilibrium.',
    usage: 'The network shows x=0 with no motion at 0 kg. An initial displacement or initial velocity cannot generate an inertial oscillation in this branch.',
    sources: ['src/physics/model.ts'],
    reconstructed: true,
    tags: ['zero mass', 'network', 'equilibrium', 'constraint'],
  },
  {
    id: 'massless-pendulum-spring',
    title: 'Zero-mass pendulum with a spring',
    scope: 'pendulum',
    group: 'Zero-mass limit',
    tex: [
      String.raw`mL^2\ddot\theta=-mgL\sin\theta-kL^2\sin\theta\cos\theta`,
      String.raw`m=0:\quad -kL^2\sin\theta\cos\theta=0`,
      String.raw`k>0,\quad |\theta|\le\pi/3\quad\Longrightarrow\quad\theta=0`,
      String.raw`\text{linear comparison:}\quad kL^2\theta=0`,
    ],
    description: 'Both rotational inertia and weight vanish with mass, while the spring torque remains. Within the available 60-degree range, its balanced stable configuration is the vertical position.',
    usage: 'At 0 kg with k>0, both pendulum modes show the equilibrium configuration. This static branch has no finite-mass oscillation or natural frequency.',
    sources: ['IMG_5921.HEIC', 'src/physics/model.ts'],
    reconstructed: true,
    tags: ['zero mass', 'pendulum', 'spring', 'torque', 'equilibrium'],
  },
  {
    id: 'massless-pendulum-free',
    title: 'Zero mass and zero spring: motion is undetermined',
    scope: 'pendulum',
    group: 'Zero-mass limit',
    tex: [
      String.raw`m=0,\quad k=0\quad\Longrightarrow\quad 0=0`,
      String.raw`\theta(t)=\theta_0\quad\text{is the display convention}`, 
    ],
    description: 'There is no inertia, weight, or spring torque. The balance provides no equation that determines angular acceleration or a unique motion.',
    usage: 'The simulation holds the chosen angle as an illustration. Its stationary display is a convention, not a predicted oscillation, and no natural frequency is assigned.',
    sources: ['IMG_5921.HEIC', 'src/physics/model.ts'],
    reconstructed: true,
    tags: ['zero mass', 'zero spring', 'indeterminate', 'display convention'],
  },
  {
    id: 'massless-pendulum-division',
    title: 'Dividing the pendulum equation requires positive mass',
    scope: 'pendulum',
    group: 'Zero-mass limit',
    tex: [
      String.raw`\ddot\theta=-\frac gL\sin\theta-\frac km\sin\theta\cos\theta\quad(m>0)`,
      String.raw`k=0,\ m>0:\quad\ddot\theta=-\frac gL\sin\theta`,
      String.raw`k=0,\ m=0:\quad 0=0`,
    ],
    description: 'The mass-independent simple-pendulum equation follows by canceling a nonzero mass. That cancellation is invalid at exactly zero mass.',
    usage: 'Use the divided acceleration equation only for m>0. At 0 kg the undivided torque balance selects the separate constraint or indeterminate branch.',
    sources: ['IMG_5921.HEIC', 'src/physics/model.ts'],
    reconstructed: true,
    tags: ['zero mass', 'division by zero', 'simple pendulum', 'assumptions'],
  },
]
