import type { FormulaEntry } from './formulaTypes'

/** Photo-backed lecture foundations plus explicitly reconstructed mathematical steps. */
export const foundationFormulas: FormulaEntry[] = [
  {
    id: "foundation-a01",
    title: "Newton’s second law and acceleration notation",
    scope: "shared",
    group: "Motion and forces",
    tex: [
      String.raw`\sum F_x=m\ddot{x}`,
      String.raw`\dot{x}=dx/dt,\quad \ddot{x}=d^2x/dt^2`,
    ],
    description: "Use signed force components along the chosen positive axis; network uses downward positive.",
    usage: "Choose an axis, resolve signed forces, and equate their sum to mass times acceleration.",
    sources: ["IMG_5901.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a02",
    title: "Linear spring restoring force",
    scope: "shared",
    group: "Motion and forces",
    tex: [
      String.raw`F_s=-kx`,
    ],
    description: "x is signed displacement/extension from the applicable equilibrium. The minus sign denotes restoring direction.",
    usage: "Use the spring extension and its sign to find the restoring force.",
    sources: ["IMG_5901.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a03",
    title: "Undamped translational equation of motion",
    scope: "shared",
    group: "Motion and forces",
    tex: [
      String.raw`m\ddot{x}+kx=0`,
    ],
    description: "For the network substitute k_eq for k. The small-angle pendulum has the analogous linear equation J thetaDDot+K_theta theta=0; full-trig mode retains nonlinear sine and cosine terms.",
    usage: "Use this for the network and the small-angle pendulum comparison.",
    sources: ["IMG_5901.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a04",
    title: "Exponential trial solution and derivatives",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`x=Ce^{st}`,
      String.raw`\dot{x}=sCe^{st}`,
      String.raw`\ddot{x}=s^2Ce^{st}`,
    ],
    description: "Analytical derivation support for the network and small-angle pendulum. The full-trig pendulum does not have this harmonic trial solution.",
    usage: "Substitute the trial solution into the differential equation to reduce it to algebra.",
    sources: ["IMG_5902.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a05",
    title: "Characteristic equation and natural angular frequency",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`ms^2+k=0`,
      String.raw`s=\pm i\sqrt{k/m}=\pm i\omega_n`,
      String.raw`\omega_n=\sqrt{k/m}`,
    ],
    description: "Generalize m,k to inertia M and stiffness K for a linear model. This gives the network frequency and the pendulum’s small-angle natural frequency.",
    usage: "Identify the sinusoidal frequency from the imaginary characteristic roots.",
    sources: ["IMG_5902.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a06",
    title: "Exponential and real general solutions",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`x=C_1e^{i\omega_nt}+C_2e^{-i\omega_nt}`,
      String.raw`x=A_1\sin(\omega_nt)+A_2\cos(\omega_nt)`,
    ],
    description: "For real motion the complex constants are conjugate; real sine/cosine constants avoid complex arithmetic.",
    usage: "Use the two constants to satisfy displacement and velocity initial conditions. Applies to the network and small-angle pendulum, not the full-trig response.",
    sources: ["IMG_5902.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a07",
    title: "Euler identities",
    scope: "shared",
    group: "Trigonometry",
    tex: [
      String.raw`e^{i\alpha}=\cos\alpha+i\sin\alpha`,
      String.raw`e^{-i\alpha}=\cos\alpha-i\sin\alpha`,
    ],
    description: "Explains conversion from imaginary characteristic roots to real harmonic motion.",
    usage: "Convert complex exponentials into real sine and cosine functions.",
    sources: ["IMG_5902.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a08",
    title: "Amplitude–phase form and sine addition",
    scope: "shared",
    group: "Trigonometry",
    tex: [
      String.raw`x=A\sin(\omega_nt+\phi)`,
      String.raw`\sin(a+b)=\sin a\cos b+\cos a\sin b`,
      String.raw`A_1=A\cos\phi,\quad A_2=A\sin\phi`,
    ],
    description: "The addition identity is the implied algebra underlying the stated A1/A2 relations. Do not mix sine and cosine phase conventions.",
    usage: "Compare coefficients after expanding sin(omega_n t + phi). Applies to the network and small-angle pendulum, not the full-trig response.",
    sources: ["IMG_5902.HEIC"],
    reconstructed: true,
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a09",
    title: "Initial-condition equations for sine phase convention",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`x(0)=x_0=A\sin\phi`,
      String.raw`\dot{x}(0)=v_0=A\omega_n\cos\phi`,
    ],
    description: "Initial-condition equations for sine phase convention.",
    usage: "Apply t=0 to determine the two constants in the harmonic response. Applies to the network and small-angle pendulum, not the full-trig response.",
    sources: ["IMG_5902.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a10",
    title: "Pythagorean trig identity and response amplitude",
    scope: "shared",
    group: "Trigonometry",
    tex: [
      String.raw`\sin^2\phi+\cos^2\phi=1`,
      String.raw`A=\sqrt{x_0^2+(v_0/\omega_n)^2}`,
    ],
    description: "Amplitude depends on initial velocity as well as initial displacement.",
    usage: "Compute the full oscillation amplitude, including a nonzero initial velocity. Applies to the network and small-angle pendulum, not the full-trig response.",
    sources: ["IMG_5902.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a11",
    title: "Phase from initial conditions, with correct quadrant",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`\tan\phi=\omega_nx_0/v_0`,
      String.raw`\phi=\operatorname{atan2}(\omega_nx_0,v_0)`,
    ],
    description: "The photo writes one-argument arctan(omega_n*x0/v0). atan2 is the complete form; phase is arbitrary/undefined if both initial conditions vanish. One-argument arctan is insufficient when v0<0 and divides by zero when v0=0.",
    usage: "Use atan2 instead of a ratio alone so negative or zero initial velocity is handled correctly. Applies to the network and small-angle pendulum, not the full-trig response.",
    sources: ["IMG_5902.HEIC"],
    reconstructed: true,
    correction: "The photo’s one-argument inverse tangent loses the quadrant and is undefined as written when v0=0. Use atan2; if A=0, phase has no physical meaning.",
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a12",
    title: "Initial-condition response for the linear models",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`q(t)=q_0\cos(\omega_nt)+\frac{\dot q_0}{\omega_n}\sin(\omega_nt)`,
      String.raw`\dot q(t)=-q_0\omega_n\sin(\omega_nt)+\dot q_0\cos(\omega_nt)`,
      String.raw`\ddot q(t)=-\omega_n^2q(t)`,
      String.raw`A_q=\sqrt{q_0^2+(\dot q_0/\omega_n)^2}`,
    ],
    description: "Derived from the photo’s sine/cosine coefficients and initial conditions. q=theta for the small-angle pendulum, q=x for the network.",
    usage: "This is the analytical trajectory for the network and the small-angle pendulum mode. The full-trig pendulum uses its nonlinear equation instead.",
    sources: ["IMG_5902.HEIC"],
    reconstructed: true,
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a13",
    title: "Vertical static equilibrium",
    scope: "shared",
    group: "Motion and forces",
    tex: [
      String.raw`W=mg=k\delta_{st}`,
      String.raw`\delta_{st}=mg/k`,
      String.raw`k=mg/\delta_{st}`,
    ],
    description: "Directly applies to the pictured single vertical spring; replace k by k_eq for an equivalent network measured from a consistently defined unloaded datum.",
    usage: "Find the resting deformation before writing a vertical-motion equation.",
    sources: ["IMG_5903 2.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a14",
    title: "Gravity cancels from incremental vertical EOM",
    scope: "shared",
    group: "Motion and forces",
    tex: [
      String.raw`mg-k(\delta_{st}+x)=m\ddot{x}`,
      String.raw`mg-k\delta_{st}=0`,
      String.raw`m\ddot{x}+kx=0`,
    ],
    description: "x is displacement from static equilibrium, not spring’s total stretch. This explains why the network’s linear frequency has no explicit g term.",
    usage: "Define x from static equilibrium so constant weight and preload terms cancel.",
    sources: ["IMG_5903 2.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a15",
    title: "Frequency from static sag",
    scope: "lecture",
    group: "Lecture background",
    tex: [
      String.raw`\omega_n=\sqrt{k/m}=\sqrt{g/\delta_{st}}`,
    ],
    description: "Use only when delta_st is the static sag due to mg under the same effective vertical stiffness; not the pendulum angle or the network’s oscillation amplitude.",
    usage: "Infer natural frequency from a measured static sag under the same linear stiffness.",
    sources: ["IMG_5903 2.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a16",
    title: "Periodic and harmonic motion",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`x(t+\tau)=x(t)`,
      String.raw`x(t)=A\sin(\omega t)`,
      String.raw`\alpha(t)=\omega t`,
    ],
    description: "The first relation defines periodic motion; the sinusoid is the more specific harmonic case. The full-trig pendulum oscillation is periodic but not exactly harmonic. Alpha is phase, not the bob angle.",
    usage: "Recognize repeated motion and distinguish oscillation phase from the physical coordinate.",
    sources: ["IMG_5904.HEIC"],
    reconstructed: true,
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a17",
    title: "Frequency, circular frequency, period, and one cycle",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`f=1/\tau`,
      String.raw`\tau=1/f`,
      String.raw`\omega\tau=2\pi`,
      String.raw`\omega=2\pi f=2\pi/\tau`,
      String.raw`f=\omega/(2\pi),\quad\tau=2\pi/\omega`,
    ],
    description: "f in Hz (cycles/s), omega in rad/s, period in s; a full cycle spans 2 pi radians.",
    usage: "Convert actual period to cycle frequency using f=1/period. In full-trig pendulum mode, actual 2 pi/period differs from the displayed small-angle natural omega_n.",
    sources: ["IMG_5904.HEIC", "IMG_5905.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a18",
    title: "Velocity and acceleration of harmonic response",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`x=A\sin(\omega_nt+\phi)`,
      String.raw`v=A\omega_n\cos(\omega_nt+\phi)`,
      String.raw`a=-A\omega_n^2\sin(\omega_nt+\phi)=-\omega_n^2x`,
      String.raw`v_{max}=A\omega_n,\quad |a|_{max}=A\omega_n^2`,
    ],
    description: "Differentiated from the photographed response. Speed is greatest at equilibrium; acceleration is zero there. At either displacement extreme, v=0 and |a| is greatest.",
    usage: "Find speed, acceleration, and their maxima from the displacement curve. Applies to the network and small-angle pendulum, not the full-trig response.",
    sources: ["IMG_5902.HEIC", "IMG_5905.HEIC"],
    reconstructed: true,
    correction: "At equilibrium it is speed, the magnitude of velocity, that is maximum; signed velocity alternates between positive and negative values.",
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a19",
    title: "Phase shift versus time shift",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`A\sin(\omega_nt+\phi)=A\sin\{\omega_n(t+\phi/\omega_n)\}`,
      String.raw`\Delta t=\phi/\omega_n`,
    ],
    description: "For +phi in the sine argument, the graph shifts left by phi/omega_n. The photo’s origin-to-first-peak definition is not generally the phase angle.",
    usage: "Translate a phase offset into a horizontal displacement of the response graph. Applies to the network and small-angle pendulum, not the full-trig response.",
    sources: ["IMG_5905.HEIC"],
    reconstructed: true,
    correction: "The source calls phase the angle to the first peak. With the displayed sine convention, that peak occurs at omega_n*t = pi/2 − phi (mod 2 pi).",
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a20",
    title: "Peak times for the sine phase convention",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`\omega_nt_{peak}+\phi=\pi/2+2\pi n`,
      String.raw`t_{peak}=\frac{\pi/2-\phi+2\pi n}{\omega_n}`,
    ],
    description: "Use an integer n giving the desired nonnegative peak time. Added to resolve the photographed phase/peak inconsistency.",
    usage: "Locate a displacement maximum without mistaking its time for the phase angle. Applies to the network and small-angle pendulum, not the full-trig response.",
    sources: ["IMG_5905.HEIC"],
    reconstructed: true,
    correction: "The source calls phase the angle to the first peak. With the displayed sine convention, that peak occurs at omega_n*t = pi/2 − phi (mod 2 pi).",
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a21",
    title: "Inclined-plane force components and static equilibrium",
    scope: "lecture",
    group: "Lecture background",
    tex: [
      String.raw`W_{parallel}=mg\sin\beta`,
      String.raw`W_{normal}=mg\cos\beta`,
      String.raw`N=mg\cos\beta`,
      String.raw`k\delta_{st}=mg\sin\beta`,
    ],
    description: "Beta denotes the fixed slope angle to avoid confusion with the dynamic pendulum coordinate.",
    usage: "Resolve gravity along and normal to a ramp in the separate lecture example.",
    sources: ["IMG_5906.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a22",
    title: "Inclined spring–mass EOM measured from equilibrium",
    scope: "lecture",
    group: "Lecture background",
    tex: [
      String.raw`mg\sin\beta-k(\delta_{st}+x)=m\ddot{x}`,
      String.raw`m\ddot{x}+kx=0`,
      String.raw`\omega_n=\sqrt{k/m}`,
    ],
    description: "Separate inclined-system example. Its same equilibrium-cancellation reasoning supports the vertical network.",
    usage: "Show why a fixed ramp angle changes the static position but not this linear frequency.",
    sources: ["IMG_5906.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a23",
    title: "Normal-force components in horizontal/vertical axes",
    scope: "lecture",
    group: "Lecture background",
    tex: [
      String.raw`N_x=-N\sin\beta,\quad N_y=N\cos\beta`,
    ],
    description: "For the pictured ramp rising to the right, with +x right and +y up, the upward normal points left. Source arrows are geometric; signs here make axes explicit.",
    usage: "Read horizontal and vertical components using a clearly stated sign convention.",
    sources: ["IMG_5907.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a24",
    title: "Complementary-angle identities",
    scope: "shared",
    group: "Trigonometry",
    tex: [
      String.raw`\sin(\pi/2-\beta)=\cos\beta`,
      String.raw`\cos(\pi/2-\beta)=\sin\beta`,
    ],
    description: "Derived support for the 90°−theta angle construction and force projection; radians are used in formulas.",
    usage: "Convert sine to cosine when the diagram provides the complementary angle.",
    sources: ["IMG_5907.HEIC"],
    reconstructed: true,
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a25",
    title: "Parallelogram properties",
    scope: "lecture",
    group: "Lecture background",
    tex: [
      String.raw`AB\parallel CD,\quad AD\parallel BC`,
      String.raw`|AB|=|CD|,\quad|AD|=|BC|`,
      String.raw`\angle A=\angle C,\quad\angle B=\angle D`,
      String.raw`|AO|=|OC|,\quad|BO|=|OD|`,
    ],
    description: "Geometry reference. O is intersection of diagonals; side-length and angle equalities are distinct.",
    usage: "Recover equal sides and angles when constructing a force-component diagram.",
    sources: ["IMG_5908.HEIC"],
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-a26",
    title: "Parallel-line angle relationships",
    scope: "lecture",
    group: "Lecture background",
    tex: [
      String.raw`\text{Corresponding: }a=e,\ b=f,\ c=g,\ d=h`,
      String.raw`\text{Vertical: }a=c,\ b=d,\ e=g,\ f=h`,
      String.raw`\text{Alternate interior: }d=f,\ c=e`,
      String.raw`\text{Alternate exterior: }a=g,\ b=h`,
      String.raw`\text{Adjacent on a line: }a+b=\pi`,
    ],
    description: "For the photo’s two parallel lines and transversal, a,b,c,d label the upper intersection clockwise from upper-left; e,f,g,h do the same at the lower intersection. The supplementary-angle equation is added supporting geometry.",
    usage: "Transfer angles between parallel lines to identify the angle used in a projection.",
    sources: ["IMG_5908.HEIC"],
    reconstructed: true,
    tags: ["foundation", "lecture-photo"],
  },
  {
    id: "foundation-radians",
    title: "Degrees, radians, and arc length",
    scope: "shared",
    group: "Trigonometry",
    tex: [
      String.raw`\theta_{\mathrm{rad}}=\frac{\pi}{180}\theta_{\mathrm{deg}}`,
      String.raw`\theta_{\mathrm{deg}}=\frac{180}{\pi}\theta_{\mathrm{rad}}`,
      String.raw`s=r\theta\quad(\theta\text{ in radians})`,
    ],
    description: "A radian measures arc length divided by radius; one full turn is 2 pi radians or 360 degrees.",
    usage: "Convert the angle and angular-rate controls to radians before using motion, torque, and energy equations.",
    sources: ["IMG_5904.HEIC", "Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-right-triangle",
    title: "Right-triangle trigonometry",
    scope: "shared",
    group: "Trigonometry",
    tex: [
      String.raw`\sin\theta=\frac{\text{opposite}}{\text{hypotenuse}}`,
      String.raw`\cos\theta=\frac{\text{adjacent}}{\text{hypotenuse}}`,
      String.raw`\tan\theta=\frac{\text{opposite}}{\text{adjacent}}=\frac{\sin\theta}{\cos\theta}`,
      String.raw`a^2+b^2=c^2`,
    ],
    description: "A component along an axis uses cosine of the angle from that axis; the perpendicular component uses sine.",
    usage: "Derive pendulum geometry and resolve forces from the angle actually marked in a diagram.",
    sources: ["IMG_5906.HEIC", "IMG_5907.HEIC"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-parity",
    title: "Sine and cosine under a sign change",
    scope: "shared",
    group: "Trigonometry",
    tex: [
      String.raw`\sin(-\theta)=-\sin\theta`,
      String.raw`\cos(-\theta)=\cos\theta`,
    ],
    description: "Sine changes sign while cosine is unchanged when the angle reverses.",
    usage: "Check that the pendulum moves left/right symmetrically and that its vertical rise is the same on either side.",
    sources: ["Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-cos-addition",
    title: "Cosine addition and phase equivalence",
    scope: "shared",
    group: "Trigonometry",
    tex: [
      String.raw`\cos(a+b)=\cos a\cos b-\sin a\sin b`,
      String.raw`\sin\alpha=\cos(\alpha-\pi/2)`,
      String.raw`A\sin(\omega t+\phi)=A\cos(\omega t+\phi-\pi/2)`,
    ],
    description: "Sine and cosine describe the same harmonic motion with different phase origins.",
    usage: "Keep the chosen phase convention consistent when comparing formulas or plotting a response.",
    sources: ["IMG_5902.HEIC", "IMG_5905.HEIC"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-small-angle",
    title: "Small-angle approximations",
    scope: "shared",
    group: "Trigonometry",
    tex: [
      String.raw`\sin\theta=\theta-\theta^3/6+\cdots\approx\theta`,
      String.raw`\cos\theta=1-\theta^2/2+\cdots`,
      String.raw`\tan\theta\approx\theta`,
      String.raw`1-\cos\theta\approx\theta^2/2`,
    ],
    description: "These approximations require radians. Keeping the quadratic term in 1−cos(theta) is essential for gravitational potential energy.",
    usage: "Linearize restoring moments and spring displacement while retaining the leading nonzero energy terms.",
    sources: ["Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-pendulum-geometry",
    title: "Pendulum projections and vertical rise",
    scope: "pendulum",
    group: "Trigonometry",
    tex: [
      String.raw`x_{\mathrm{draw}}=l\sin\theta,\qquad y_{\mathrm{draw}}=l\cos\theta`,
      String.raw`h=l-l\cos\theta=l(1-\cos\theta)`,
      String.raw`x_{\mathrm{linear}}=l\theta,\qquad h\approx\frac12l\theta^2`,
    ],
    description: "Drawing y is measured downward from the pivot. Full-trig mode uses l sin(theta) as its horizontal coordinate; the small-angle comparison uses l theta.",
    usage: "Distinguish full-trig horizontal geometry from the first-order coordinate used only in small-angle dynamics.",
    sources: ["Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-derivative-linearity",
    title: "Derivative notation and linearity",
    scope: "shared",
    group: "Calculus",
    tex: [
      String.raw`\dot q=\frac{dq}{dt},\qquad\ddot q=\frac{d^2q}{dt^2}`,
      String.raw`\frac{d}{dt}[af(t)+bg(t)]=a f'(t)+b g'(t)`,
      String.raw`\frac{dC}{dt}=0`,
    ],
    description: "The coefficients a, b, and C are constants with respect to time.",
    usage: "Differentiate a sum of restoring terms or sine/cosine components one term at a time.",
    sources: ["IMG_5901.HEIC", "IMG_5902.HEIC"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-power-chain",
    title: "Power and chain rules",
    scope: "shared",
    group: "Calculus",
    tex: [
      String.raw`\frac{d}{dz}z^n=nz^{n-1}`,
      String.raw`\frac{d}{dt}f(u(t))=f'(u(t))\dot u(t)`,
      String.raw`\frac{d}{dt}[q(t)^2]=2q\dot q`,
    ],
    description: "A time-dependent inner argument contributes its own derivative.",
    usage: "Differentiate squared energies and recover the omega factor when differentiating a harmonic phase.",
    sources: ["IMG_5902.HEIC", "Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-product-quotient",
    title: "Product and quotient rules",
    scope: "lecture",
    group: "Calculus",
    tex: [
      String.raw`\frac{d}{dt}(uv)=\dot u\,v+u\,\dot v`,
      String.raw`\frac{d}{dt}\left(\frac uv\right)=\frac{\dot u\,v-u\,\dot v}{v^2}\quad(v\ne0)`,
    ],
    description: "These are general supporting calculus rules; constant physical parameters simplify many terms in this model.",
    usage: "Check a derivative of a product or ratio instead of treating variable factors as constants.",
    sources: [],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-trig-derivatives",
    title: "Sine, cosine, and exponential derivatives",
    scope: "shared",
    group: "Calculus",
    tex: [
      String.raw`\frac{d}{dz}\sin z=\cos z,\qquad\frac{d}{dz}\cos z=-\sin z`,
      String.raw`\frac{d}{dt}\sin(\omega t+\phi)=\omega\cos(\omega t+\phi)`,
      String.raw`\frac{d}{dt}\cos(\omega t+\phi)=-\omega\sin(\omega t+\phi)`,
      String.raw`\frac{d}{dt}e^{st}=se^{st}`,
    ],
    description: "The phase constants omega, phi, and s do not vary during one trajectory. Trigonometric derivative formulas use radians.",
    usage: "Generate velocity and acceleration from displacement or verify the exponential trial solution.",
    sources: ["IMG_5902.HEIC"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-partial-derivatives",
    title: "Partial versus total derivatives in Lagrange’s equation",
    scope: "shared",
    group: "Calculus",
    tex: [
      String.raw`\frac{\partial}{\partial q}\left(\frac12M\dot q^2\right)=0`,
      String.raw`\frac{\partial}{\partial\dot q}\left(\frac12M\dot q^2\right)=M\dot q`,
      String.raw`\frac{d}{dt}(M\dot q)=M\ddot q`,
      String.raw`\frac{\partial}{\partial q}\left(\frac12Kq^2\right)=Kq`,
    ],
    description: "Treat q and qDot as independent variables when taking the indicated partial derivative; take the time derivative afterward. M and K are constant here.",
    usage: "Evaluate the kinetic and potential terms in Lagrange’s equation for either single-coordinate model.",
    sources: ["Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-total-chain",
    title: "Total derivative of a state-dependent function",
    scope: "shared",
    group: "Calculus",
    tex: [
      String.raw`\frac{d}{dt}F(q,\dot q,t)=\frac{\partial F}{\partial q}\dot q+\frac{\partial F}{\partial\dot q}\ddot q+\frac{\partial F}{\partial t}`,
    ],
    description: "A total time derivative accounts for every time-dependent argument.",
    usage: "Understand why d/dt(partial T/partial qDot) produces inertia times acceleration.",
    sources: ["Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-spring-work",
    title: "Spring energy from work",
    scope: "shared",
    group: "Calculus",
    tex: [
      String.raw`U_s(x)=\int_0^x k\xi\,d\xi=\frac12kx^2`,
      String.raw`F_s=-\frac{dU_s}{dx}=-kx`,
    ],
    description: "Stored spring energy is nonnegative for either signed extension, while its derivative gives the restoring-force direction.",
    usage: "Connect Hooke’s law to potential energy instead of memorizing the energy formula in isolation.",
    sources: ["IMG_5901.HEIC", "Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-energy-rate",
    title: "Energy conservation from the equation of motion",
    scope: "shared",
    group: "Calculus",
    tex: [
      String.raw`E=\frac12M\dot q^2+\frac12Kq^2`,
      String.raw`\frac{dE}{dt}=\dot q(M\ddot q+Kq)=0`,
    ],
    description: "For constant M and K with no damping or forcing, the equation of motion makes the total-energy rate zero.",
    usage: "Verify the simulation’s constant total-energy trace and the exchange between kinetic and potential energy.",
    sources: ["IMG_5901.HEIC", "Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-frequency-general",
    title: "Generalized stiffness and frequency",
    scope: "shared",
    group: "Harmonic motion",
    tex: [
      String.raw`M\ddot q+Kq=0`,
      String.raw`\omega_n=\sqrt{K/M}`,
      String.raw`K=M\omega_n^2`,
    ],
    description: "M is generalized inertia, so it is m for a translating mass and J for a rotating body. K must correspond to that same coordinate.",
    usage: "Use this oscillator solution for the vertical network and the small-angle pendulum only. The full-trig model has no constant stiffness multiplying theta.",
    sources: ["IMG_5901.HEIC", "IMG_5902.HEIC", "Adobe Scan Oct 4, 2026.pdf"],
    reconstructed: true,
    tags: ["foundation", "supporting-derivation"],
  },
  {
    id: "foundation-classification",
    title: "Periodic and deterministic are different properties",
    scope: "shared",
    group: "Motion and forces",
    tex: [
      String.raw`q(t+\tau)=q(t)\quad\text{for a periodic trajectory}`,
    ],
    description: "Deterministic motion can be predicted from its governing equations and initial conditions. Periodic motion repeats after a fixed interval; deterministic motion need not be periodic.",
    usage: "Both simulations are free, undamped, deterministic and have one degree of freedom. The network and small-angle pendulum are linear and harmonic; the full-trig pendulum is nonlinear and its bounded oscillations are periodic but not exactly harmonic.",
    sources: ["IMG_5899.HEIC", "IMG_5900.HEIC", "IMG_5904.HEIC"],
    reconstructed: true,
    correction: "The handwriting in IMG_5900 labels predictable motion “periodic.” That definition is deterministic; the two labels are not interchangeable.",
    tags: ["foundation", "supporting-derivation"],
  },
]
